import { useEffect, useMemo, useState, type Dispatch, type SetStateAction } from "react";
import { Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import type { OfferCatalogVariant, OfferDefinition, OfferProductRole, OfferScopeType, OfferType, OfferVersion } from "../contracts";
import { buildOfferVersionPayload, emptyOfferVersionForm, offerVersionToForm, type OfferVersionForm } from "../formUtils";
import { EditorDialog, EditorField, editorInputClass, editorSelectClass } from "../EditorDialog";

export function OfferDefinitionEditor({ open, definition, pending, onClose, onSave }: {
  open: boolean; definition: OfferDefinition | null; pending: boolean; onClose: () => void;
  onSave: (input: { code: string; name: string; description: string | null }) => void;
}) {
  const [code, setCode] = useState(""); const [name, setName] = useState(""); const [description, setDescription] = useState("");
  useEffect(() => { if (open) { setCode(definition?.code ?? ""); setName(definition?.name ?? ""); setDescription(definition?.description ?? ""); } }, [definition, open]);
  return <EditorDialog open={open} onClose={onClose} title={definition ? "تعديل تعريف العرض" : "إنشاء عرض جديد"} subtitle="التعريف هو الهوية الثابتة؛ قواعد التنفيذ توضع داخل النسخ."
    footer={<><button className="commercial-editor-button commercial-editor-button--ghost" onClick={onClose}>إلغاء</button><button className="commercial-editor-button commercial-editor-button--primary" disabled={pending} onClick={() => { try { const cleanCode = code.trim().toUpperCase(); const cleanName = name.trim(); if (!cleanCode || !cleanName) throw new Error("كود واسم العرض مطلوبان."); onSave({ code: cleanCode, name: cleanName, description: description.trim() || null }); } catch (error) { toast.error(error instanceof Error ? error.message : "بيانات العرض غير صالحة."); } }}>{pending ? "جاري الحفظ..." : "حفظ التعريف"}</button></>}>
    <div className="commercial-editor-grid commercial-editor-grid--2"><EditorField label="الكود الثابت"><input className={editorInputClass} value={code} onChange={(e) => setCode(e.target.value)} maxLength={100} dir="ltr" /></EditorField><EditorField label="اسم العرض"><input className={editorInputClass} value={name} onChange={(e) => setName(e.target.value)} maxLength={150} /></EditorField></div>
    <EditorField label="الوصف"><textarea className={`${editorInputClass} min-h-24 resize-y`} value={description} onChange={(e) => setDescription(e.target.value)} maxLength={2000} /></EditorField>
  </EditorDialog>;
}

function VariantTarget({ value, onChange, variants, catalogAvailable }: { value: string; onChange: (value: string) => void; variants: OfferCatalogVariant[]; catalogAvailable: boolean }) {
  if (!catalogAvailable) return <input className={editorInputClass} value={value} onChange={(e) => onChange(e.target.value)} inputMode="numeric" placeholder="Product Variant ID" dir="ltr" />;
  return <select className={editorSelectClass} value={value} onChange={(e) => onChange(e.target.value)}><option value="">اختر الصنف</option>{variants.map((row) => <option key={row.id} value={row.id}>{row.name} — {row.sku}</option>)}</select>;
}

function UomTarget({ variantId, value, onChange, variants, catalogAvailable, allowAny = false }: { variantId: string; value: string; onChange: (value: string) => void; variants: OfferCatalogVariant[]; catalogAvailable: boolean; allowAny?: boolean }) {
  if (!catalogAvailable) return <input className={editorInputClass} value={value} onChange={(e) => onChange(e.target.value)} inputMode="numeric" placeholder={allowAny ? "UOM ID — فارغ = كل الوحدات" : "UOM ID"} dir="ltr" />;
  const variant = variants.find((row) => String(row.id) === variantId);
  return <select className={editorSelectClass} value={value} onChange={(e) => onChange(e.target.value)} disabled={!variantId || !variant}><option value="">{allowAny ? "كل الوحدات" : variantId ? "اختر الوحدة" : "اختر الصنف أولاً"}</option>{variant?.uoms.map((uom) => <option key={uom.id} value={uom.id}>{uom.name} — {uom.code}</option>)}</select>;
}

function PayloadFields({ form, setForm }: { form: OfferVersionForm; setForm: Dispatch<SetStateAction<OfferVersionForm>> }) {
  const set = <K extends keyof OfferVersionForm>(key: K, value: OfferVersionForm[K]) => setForm((current) => ({ ...current, [key]: value }));
  if (form.offer_type === "PERCENTAGE_DISCOUNT") return <EditorField label="نسبة الخصم %"><input className={editorInputClass} value={form.percentage} onChange={(e) => set("percentage", e.target.value)} inputMode="decimal" dir="ltr" /></EditorField>;
  if (form.offer_type === "FIXED_DISCOUNT") return <EditorField label="قيمة الخصم الثابت"><input className={editorInputClass} value={form.fixed_amount} onChange={(e) => set("fixed_amount", e.target.value)} inputMode="decimal" dir="ltr" /></EditorField>;
  if (form.offer_type === "BUY_X_GET_Y") return <EditorField label="كمية الشراء المؤهلة" hint="تُقاس بوحدة المنتجات المؤهلة؛ كل المكافآت تحدد كميتها في صفها أدناه."><input className={editorInputClass} value={form.buy_quantity} onChange={(e) => set("buy_quantity", e.target.value)} inputMode="decimal" dir="ltr" /></EditorField>;
  if (form.offer_type === "FREE_GOODS") return <EditorField label="الكمية المؤهلة" hint="تُقاس بوحدة المنتجات المؤهلة؛ كل مكافأة لها وحدتها وكميتها الخاصة."><input className={editorInputClass} value={form.qualifying_quantity} onChange={(e) => set("qualifying_quantity", e.target.value)} inputMode="decimal" dir="ltr" /></EditorField>;
  if (form.offer_type === "QUANTITY_TIERS") return <div className="commercial-editor-section"><div className="commercial-editor-section-head"><div><strong>شرائح الكمية</strong><small>الحدود تصاعدية وبدون تكرار.</small></div><button className="commercial-editor-mini" type="button" onClick={() => set("tiers", [...form.tiers, { minimum_quantity: "", reward_type: "PERCENTAGE_DISCOUNT", reward_value: "" }])}><Plus className="h-3.5 w-3.5" /> شريحة</button></div><div className="space-y-2">{form.tiers.map((tier, index) => <div key={index} className="commercial-editor-row commercial-editor-row--tier"><input className={editorInputClass} value={tier.minimum_quantity} onChange={(e) => set("tiers", form.tiers.map((row, i) => i === index ? { ...row, minimum_quantity: e.target.value } : row))} placeholder="من كمية" inputMode="decimal" dir="ltr" /><select className={editorSelectClass} value={tier.reward_type} onChange={(e) => set("tiers", form.tiers.map((row, i) => i === index ? { ...row, reward_type: e.target.value as typeof row.reward_type } : row))}><option value="PERCENTAGE_DISCOUNT">خصم نسبي</option><option value="FIXED_DISCOUNT">خصم ثابت</option><option value="FREE_QUANTITY">كمية مجانية</option></select><input className={editorInputClass} value={tier.reward_value} onChange={(e) => set("tiers", form.tiers.map((row, i) => i === index ? { ...row, reward_value: e.target.value } : row))} placeholder="القيمة" inputMode="decimal" dir="ltr" /><button type="button" className="commercial-editor-icon-button" disabled={form.tiers.length === 1} onClick={() => set("tiers", form.tiers.filter((_, i) => i !== index))}><Trash2 className="h-4 w-4" /></button></div>)}</div></div>;
  return <div className="commercial-editor-grid commercial-editor-grid--2"><EditorField label="نوع مكافأة الحزمة"><select className={editorSelectClass} value={form.bundle_reward_type} onChange={(e) => set("bundle_reward_type", e.target.value as OfferVersionForm["bundle_reward_type"])}><option value="PERCENTAGE_DISCOUNT">خصم نسبي</option><option value="FIXED_DISCOUNT">خصم ثابت</option><option value="FIXED_PRICE">سعر حزمة ثابت</option></select></EditorField><EditorField label="قيمة مكافأة الحزمة"><input className={editorInputClass} value={form.bundle_reward_value} onChange={(e) => set("bundle_reward_value", e.target.value)} inputMode="decimal" dir="ltr" /></EditorField></div>;
}

const roleLabel: Record<OfferProductRole, string> = { QUALIFYING: "منتج مؤهل", REWARD: "منتج مكافأة", BUNDLE_COMPONENT: "مكوّن حزمة" };

export function OfferVersionEditor({ open, definition, version, variants, catalogAvailable, hasMoreVariants, loadingMoreVariants, onLoadMoreVariants, pending, onClose, onSave }: {
  open: boolean; definition: OfferDefinition | null; version: OfferVersion | null; variants: OfferCatalogVariant[]; catalogAvailable: boolean;
  hasMoreVariants: boolean; loadingMoreVariants: boolean; onLoadMoreVariants: () => void; pending: boolean; onClose: () => void; onSave: (payload: Record<string, unknown>) => void;
}) {
  const [form, setForm] = useState<OfferVersionForm>(emptyOfferVersionForm());
  useEffect(() => { if (open) setForm(version ? offerVersionToForm(version) : emptyOfferVersionForm()); }, [open, version]);
  const productRoleOptions = useMemo<OfferProductRole[]>(() => ["BUY_X_GET_Y", "FREE_GOODS"].includes(form.offer_type) ? ["QUALIFYING", "REWARD"] : form.offer_type === "BUNDLE" ? ["BUNDLE_COMPONENT"] : [], [form.offer_type]);
  const set = <K extends keyof OfferVersionForm>(key: K, value: OfferVersionForm[K]) => setForm((current) => ({ ...current, [key]: value }));
  const isCrossProductReward = ["BUY_X_GET_Y", "FREE_GOODS"].includes(form.offer_type);
  return <EditorDialog open={open} onClose={onClose} title={version ? "تعديل نسخة العرض المسودة" : `نسخة جديدة — ${definition?.name ?? ""}`} subtitle="Typed configuration فقط؛ لا JSON حر ولا تعبيرات قابلة للتنفيذ."
    footer={<><button className="commercial-editor-button commercial-editor-button--ghost" onClick={onClose}>إلغاء</button><button className="commercial-editor-button commercial-editor-button--primary" disabled={pending} onClick={() => { try { onSave(buildOfferVersionPayload(form)); } catch (error) { toast.error(error instanceof Error ? error.message : "إعدادات العرض غير صالحة."); } }}>{pending ? "جاري الحفظ..." : version ? "حفظ المسودة" : "إنشاء المسودة"}</button></>}>
    <div className="commercial-editor-grid commercial-editor-grid--4"><EditorField label="نوع العرض"><select className={editorSelectClass} value={form.offer_type} onChange={(e) => setForm((current) => ({ ...current, offer_type: e.target.value as OfferType, products: [], scopes: [], max_reward_quantity: "" }))}><option value="PERCENTAGE_DISCOUNT">خصم نسبي</option><option value="FIXED_DISCOUNT">خصم ثابت</option><option value="BUY_X_GET_Y">اشترِ X واحصل على Y</option><option value="FREE_GOODS">بضاعة مجانية</option><option value="QUANTITY_TIERS">شرائح كمية</option><option value="BUNDLE">حزمة</option></select></EditorField><EditorField label="الأولوية"><input className={editorInputClass} value={form.priority} onChange={(e) => set("priority", e.target.value)} inputMode="numeric" dir="ltr" /></EditorField><EditorField label="التجميع"><select className={editorSelectClass} value={form.stacking_mode} onChange={(e) => set("stacking_mode", e.target.value as OfferVersionForm["stacking_mode"])}><option value="EXCLUSIVE">حصري</option><option value="STACKABLE">قابل للتجميع</option></select></EditorField><EditorField label="العملة" hint="مطلوبة إذا احتوى العرض قيمة نقدية."><input className={editorInputClass} value={form.currency_code} onChange={(e) => set("currency_code", e.target.value.toUpperCase())} maxLength={10} dir="ltr" /></EditorField></div>
    <div className="commercial-editor-grid commercial-editor-grid--2"><EditorField label="يبدأ من"><input type="datetime-local" className={editorInputClass} value={form.effective_from} onChange={(e) => set("effective_from", e.target.value)} /></EditorField><EditorField label="ينتهي في — اختياري"><input type="datetime-local" className={editorInputClass} value={form.effective_to} onChange={(e) => set("effective_to", e.target.value)} /></EditorField></div>
    <div className="commercial-editor-section"><div className="commercial-editor-section-head"><div><strong>معلمات العرض</strong><small>تتغير حسب النوع المختار.</small></div></div><PayloadFields form={form} setForm={setForm} /></div>
    <div className="commercial-editor-section"><div className="commercial-editor-section-head"><div><strong>حدود التطبيق</strong><small>{isCrossProductReward ? "في العروض متعددة الوحدات استخدم حد مرات التطبيق بدل حد كمية مكافأة عام." : "كلها اختيارية."}</small></div></div><div className="commercial-editor-grid commercial-editor-grid--3"><EditorField label="أقصى عدد تطبيقات"><input className={editorInputClass} value={form.max_applications_per_document} onChange={(e) => set("max_applications_per_document", e.target.value)} inputMode="numeric" dir="ltr" /></EditorField><EditorField label="أقصى خصم مالي"><input className={editorInputClass} value={form.max_discount_amount} onChange={(e) => set("max_discount_amount", e.target.value)} inputMode="decimal" dir="ltr" /></EditorField>{!isCrossProductReward ? <EditorField label="أقصى كمية مكافأة"><input className={editorInputClass} value={form.max_reward_quantity} onChange={(e) => set("max_reward_quantity", e.target.value)} inputMode="decimal" dir="ltr" /></EditorField> : null}</div></div>
    <div className="commercial-editor-section"><div className="commercial-editor-section-head"><div><strong>النطاقات</strong><small>القيم داخل البعد OR وبين الأبعاد AND. نطاق المنتج يمكن تقييده بوحدة محددة.</small></div><button className="commercial-editor-mini" type="button" onClick={() => set("scopes", [...form.scopes, { scope_type: "PRODUCT_VARIANT", target: "", uom_id: "" }])}><Plus className="h-3.5 w-3.5" /> نطاق</button></div><div className="space-y-2">{form.scopes.map((scope, index) => <div key={index} className="commercial-editor-row"><select className={editorSelectClass} value={scope.scope_type} onChange={(e) => set("scopes", form.scopes.map((row, i) => i === index ? { scope_type: e.target.value as OfferScopeType, target: "", uom_id: "" } : row))}><option value="PRODUCT_VARIANT">منتج</option><option value="CUSTOMER">عميل</option><option value="BRANCH">فرع</option><option value="CHANNEL">قناة</option></select>{scope.scope_type === "PRODUCT_VARIANT" ? <><VariantTarget value={scope.target} variants={variants} catalogAvailable={catalogAvailable} onChange={(value) => set("scopes", form.scopes.map((row, i) => i === index ? { ...row, target: value, uom_id: "" } : row))} /><UomTarget variantId={scope.target} value={scope.uom_id} variants={variants} catalogAvailable={catalogAvailable} allowAny={form.offer_type !== "QUANTITY_TIERS"} onChange={(value) => set("scopes", form.scopes.map((row, i) => i === index ? { ...row, uom_id: value } : row))} /></> : <input className={editorInputClass} value={scope.target} onChange={(e) => set("scopes", form.scopes.map((row, i) => i === index ? { ...row, target: e.target.value } : row))} placeholder={scope.scope_type === "CHANNEL" ? "ONLINE / RETAIL" : "ID"} dir="ltr" />}<button type="button" className="commercial-editor-icon-button" onClick={() => set("scopes", form.scopes.filter((_, i) => i !== index))}><Trash2 className="h-4 w-4" /></button></div>)}</div></div>
    {productRoleOptions.length ? <div className="commercial-editor-section"><div className="commercial-editor-section-head"><div><strong>{form.offer_type === "BUNDLE" ? "مكوّنات الحزمة" : "المنتجات المؤهلة والمكافآت"}</strong><small>{form.offer_type === "BUNDLE" ? "لكل مكوّن منتج ووحدة وكمية مطلوبة." : "يمكن أن تكون المكافأة نفس المنتج أو منتجاً آخر، ويمكن إضافة عدة مكافآت؛ لكل مكافأة وحدة وكمية مستقلة."}</small></div><button className="commercial-editor-mini" type="button" onClick={() => set("products", [...form.products, { role: productRoleOptions[0], product_variant_id: "", uom_id: "", quantity_per_application: "" }])}><Plus className="h-3.5 w-3.5" /> منتج</button></div><div className="space-y-2">{form.products.map((product, index) => <div key={index} className="commercial-editor-row"><select className={editorSelectClass} value={product.role} onChange={(e) => set("products", form.products.map((row, i) => i === index ? { ...row, role: e.target.value as OfferProductRole, quantity_per_application: e.target.value === "QUALIFYING" ? "" : row.quantity_per_application } : row))}>{productRoleOptions.map((role) => <option key={role} value={role}>{roleLabel[role]}</option>)}</select><VariantTarget value={product.product_variant_id} variants={variants} catalogAvailable={catalogAvailable} onChange={(value) => set("products", form.products.map((row, i) => i === index ? { ...row, product_variant_id: value, uom_id: "" } : row))} /><UomTarget variantId={product.product_variant_id} value={product.uom_id} variants={variants} catalogAvailable={catalogAvailable} onChange={(value) => set("products", form.products.map((row, i) => i === index ? { ...row, uom_id: value } : row))} />{product.role === "QUALIFYING" ? <input className={editorInputClass} value="" disabled placeholder="الكمية من حد التأهيل" /> : <input className={editorInputClass} value={product.quantity_per_application} onChange={(e) => set("products", form.products.map((row, i) => i === index ? { ...row, quantity_per_application: e.target.value } : row))} placeholder="الكمية لكل تطبيق" inputMode="decimal" dir="ltr" />}<button type="button" className="commercial-editor-icon-button" onClick={() => set("products", form.products.filter((_, i) => i !== index))}><Trash2 className="h-4 w-4" /></button></div>)}</div></div> : null}
    {catalogAvailable && hasMoreVariants ? <button type="button" className="commercial-load-more" disabled={loadingMoreVariants} onClick={onLoadMoreVariants}>{loadingMoreVariants ? "جاري تحميل أصناف إضافية..." : "تحميل أصناف إضافية"}</button> : null}
  </EditorDialog>;
}
