import { useEffect, useState } from "react";
import { BadgePercent, Pencil, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { useAuthFetch } from "@/hooks/useAuthFetch";
import { useInventoryAccess } from "@/hooks/useInventoryAccess";
import { createOfferDefinition, createOfferVersion, deleteOfferDefinition, deleteOfferVersion, lifecycleCommand, updateOfferDefinition, updateOfferVersion, validateVersion } from "./api";
import { useCatalogVariants, useOfferDefinitions, useOfferPolicy, useOfferVersions } from "./hooks";
import type { LifecycleStatus, OfferDefinition, OfferVersion } from "./contracts";
import { DeleteDialog } from "./DeleteDialog";
import { OfferDefinitionEditor, OfferVersionEditor } from "./editors/OfferEditors";

const statusText: Record<LifecycleStatus, string> = { DRAFT: "مسودة", PENDING_APPROVAL: "بانتظار الاعتماد", PUBLISHED: "منشورة", SUPERSEDED: "مستبدلة", CANCELLED: "ملغاة" };
const statusClass: Record<LifecycleStatus, string> = { DRAFT: "bg-amber-50 text-amber-700 ring-amber-200", PENDING_APPROVAL: "bg-sky-50 text-sky-700 ring-sky-200", PUBLISHED: "bg-emerald-50 text-emerald-700 ring-emerald-200", SUPERSEDED: "bg-slate-100 text-slate-600 ring-slate-200", CANCELLED: "bg-rose-50 text-rose-700 ring-rose-200" };
function LoadMore({ visible, pending, onClick }: { visible: boolean; pending: boolean; onClick: () => void }) { return visible ? <button className="commercial-load-more" disabled={pending} onClick={onClick}>{pending ? "جاري التحميل..." : "تحميل المزيد"}</button> : null; }

export default function OfferManagement() {
  const authFetch = useAuthFetch(); const queryClient = useQueryClient(); const access = useInventoryAccess();
  const canManage = access.isCompanyAdmin || access.canAny("offers.manage"); const canApprove = access.isCompanyAdmin || access.canAny("offers.approve"); const catalogAvailable = access.isCompanyAdmin || access.canAny("catalog.read");
  const policy = useOfferPolicy(); const definitions = useOfferDefinitions(); const catalog = useCatalogVariants(catalogAvailable);
  const [selectedId, setSelectedId] = useState<number | null>(null); const versions = useOfferVersions(selectedId); const selected = definitions.items.find((row) => row.id === selectedId) ?? null;
  const [definitionEditor, setDefinitionEditor] = useState<OfferDefinition | "new" | null>(null); const [versionEditor, setVersionEditor] = useState<OfferVersion | "new" | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<{ kind: "definition"; row: OfferDefinition } | { kind: "version"; row: OfferVersion } | null>(null); const [reason, setReason] = useState("إجراء إداري من لوحة التحكم");
  useEffect(() => { if (!definitions.items.length) { setSelectedId(null); return; } if (!selectedId || !definitions.items.some((item) => item.id === selectedId)) setSelectedId(definitions.items[0].id); }, [definitions.items, selectedId]);
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["commercial-rules", "offers"] });
  const definitionMutation = useMutation({ mutationFn: (input: { code: string; name: string; description: string | null }) => definitionEditor === "new" ? createOfferDefinition(authFetch, input) : definitionEditor ? updateOfferDefinition(authFetch, definitionEditor.id, definitionEditor.version, input) : Promise.reject(new Error("لم يتم تحديد تعريف العرض.")), onSuccess: async () => { setDefinitionEditor(null); toast.success("تم حفظ تعريف العرض."); await refresh(); } });
  const versionMutation = useMutation({ mutationFn: (payload: Record<string, unknown>) => { if (!selected) return Promise.reject(new Error("اختر تعريف العرض أولاً.")); return versionEditor === "new" ? createOfferVersion(authFetch, selected.id, selected.version, payload) : versionEditor ? updateOfferVersion(authFetch, versionEditor.id, versionEditor.version, payload) : Promise.reject(new Error("لم يتم تحديد نسخة العرض.")); }, onSuccess: async () => { setVersionEditor(null); toast.success("تم حفظ نسخة العرض المسودة."); await refresh(); } });
  const deleteMutation = useMutation({ mutationFn: (why: string) => !deleteTarget ? Promise.reject(new Error("لم يتم تحديد العنصر.")) : deleteTarget.kind === "definition" ? deleteOfferDefinition(authFetch, deleteTarget.row.id, deleteTarget.row.version, why) : deleteOfferVersion(authFetch, deleteTarget.row.id, deleteTarget.row.version, why), onSuccess: async () => { setDeleteTarget(null); toast.success("تم تنفيذ الحذف."); await refresh(); } });
  const lifecycleMutation = useMutation({ mutationFn: ({ row, action }: { row: OfferVersion; action: "submit" | "publish" | "approve" | "cancel" }) => lifecycleCommand(authFetch, "offers", row.id, action, row.version, reason.trim()), onSuccess: async () => { toast.success("تم تنفيذ إجراء العرض."); await refresh(); } });
  const validateMutation = useMutation({ mutationFn: (id: number) => validateVersion(authFetch, "offers", id), onSuccess: () => toast.success("النسخة اجتازت التحقق البنيوي.") });
  const makerChecker = policy.data?.maker_checker_enabled === true;
  return <>
    <div className="commercial-rules-offers-grid">
      <section className="commercial-rules-panel commercial-rules-panel--rail">
        <div className="commercial-section-toolbar"><div><small>Offer Catalog</small><h2>تعريفات العروض</h2></div>{canManage ? <button className="commercial-icon-action" onClick={() => setDefinitionEditor("new")}><Plus className="h-4 w-4" /></button> : null}</div>
        <div className="commercial-rules-list custom-scrollbar">{definitions.items.map((item) => <button key={item.id} onClick={() => setSelectedId(item.id)} className={`commercial-catalog-row ${selectedId === item.id ? "commercial-catalog-row--active" : ""}`}><span><strong>{item.name}</strong><small dir="ltr">{item.code}</small></span><em>v{item.version}</em></button>)}{!definitions.isPending && !definitions.items.length ? <p className="commercial-empty">لا توجد عروض حتى الآن.</p> : null}</div>
        <LoadMore visible={definitions.hasNextPage === true} pending={definitions.isFetchingNextPage} onClick={() => void definitions.fetchNextPage()} />
      </section>
      <section className="commercial-rules-panel commercial-rules-panel--main">{!selected ? <p className="commercial-empty commercial-empty--large">اختر عرضًا أو أنشئ تعريفًا جديدًا.</p> : <>
        <div className="commercial-detail-toolbar"><div className="commercial-detail-title"><span className="commercial-detail-icon"><BadgePercent className="h-4 w-4" /></span><div><h2>{selected.name}</h2><p>{selected.description || "بدون وصف."}</p></div></div>{canManage ? <div className="commercial-toolbar-actions"><button className="commercial-soft-action" onClick={() => setDefinitionEditor(selected)}><Pencil className="h-3.5 w-3.5" /> تعديل</button><button className="commercial-soft-action commercial-soft-action--danger" onClick={() => setDeleteTarget({ kind: "definition", row: selected })}><Trash2 className="h-3.5 w-3.5" /> حذف</button><button className="commercial-primary-action" onClick={() => setVersionEditor("new")}><Plus className="h-3.5 w-3.5" /> نسخة مسودة</button></div> : null}</div>
        <div className="commercial-rules-version-list custom-scrollbar">{versions.items.map((row) => <article className="commercial-version-card" key={row.id}><div className="commercial-version-head"><div><div className="commercial-version-title"><strong>{row.offer_type.replaceAll("_", " ")}</strong><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ring-1 ${statusClass[row.status]}`}>{statusText[row.status]}</span><small>r{row.revision}</small></div><div className="commercial-version-meta"><span>أولوية {row.priority}</span><span>{row.stacking_mode === "STACKABLE" ? "قابل للتجميع" : "حصري"}</span><span>{row.scopes.length} نطاق</span><span>{row.products.length} منتج مرتبط</span></div></div><div className="commercial-toolbar-actions"><button className="commercial-soft-action" onClick={() => validateMutation.mutate(row.id)}>تحقق</button>{canManage && row.status === "DRAFT" ? <><button className="commercial-soft-action" onClick={() => setVersionEditor(row)}><Pencil className="h-3.5 w-3.5" /> تعديل</button><button className="commercial-soft-action commercial-soft-action--danger" onClick={() => setDeleteTarget({ kind: "version", row })}><Trash2 className="h-3.5 w-3.5" /> حذف</button><button className="commercial-primary-action" onClick={() => lifecycleMutation.mutate({ row, action: makerChecker ? "submit" : "publish" })}>{makerChecker ? "إرسال للاعتماد" : "نشر"}</button></> : null}{canApprove && makerChecker && row.status === "PENDING_APPROVAL" ? <button className="commercial-success-action" onClick={() => lifecycleMutation.mutate({ row, action: "approve" })}>اعتماد</button> : null}{canManage && ["DRAFT", "PENDING_APPROVAL"].includes(row.status) ? <button className="commercial-danger-action" onClick={() => lifecycleMutation.mutate({ row, action: "cancel" })}>إلغاء</button> : null}</div></div><div className="commercial-evidence-strip"><div><small>Payload</small><strong>{Object.keys(row.payload).join(" · ") || "—"}</strong></div><div><small>النطاقات</small><strong>{row.scopes.length || "عام"}</strong></div><div><small>المنتجات</small><strong>{row.products.length || "—"}</strong></div></div></article>)}{!versions.isPending && !versions.items.length ? <p className="commercial-empty commercial-empty--large">لا توجد نسخ لهذا العرض.</p> : null}<LoadMore visible={versions.hasNextPage === true} pending={versions.isFetchingNextPage} onClick={() => void versions.fetchNextPage()} /></div>
        {canManage ? <div className="commercial-reason-bar"><ShieldCheck className="h-4 w-4" /><input value={reason} onChange={(e) => setReason(e.target.value)} aria-label="سبب الإجراء الإداري" /></div> : null}</>}</section>
    </div>
    <OfferDefinitionEditor open={definitionEditor !== null} definition={definitionEditor === "new" ? null : definitionEditor} pending={definitionMutation.isPending} onClose={() => setDefinitionEditor(null)} onSave={(input) => definitionMutation.mutate(input)} />
    <OfferVersionEditor open={versionEditor !== null} definition={selected} version={versionEditor === "new" ? null : versionEditor} variants={catalog.items} catalogAvailable={catalogAvailable} hasMoreVariants={catalog.hasNextPage === true} loadingMoreVariants={catalog.isFetchingNextPage} onLoadMoreVariants={() => void catalog.fetchNextPage()} pending={versionMutation.isPending} onClose={() => setVersionEditor(null)} onSave={(payload) => versionMutation.mutate(payload)} />
    <DeleteDialog open={deleteTarget !== null} title={deleteTarget?.kind === "definition" ? "حذف تعريف العرض" : "حذف نسخة العرض"} message={deleteTarget?.kind === "definition" ? "يمكن حذف التعريف فقط إذا لم يعد لديه تاريخ نسخ يمنع الحذف." : "الحذف مسموح للمسودة فقط."} pending={deleteMutation.isPending} onClose={() => setDeleteTarget(null)} onConfirm={(why) => deleteMutation.mutate(why)} />
  </>;
}
