import { useEffect, useState } from "react";
import { Pencil, Plus, Scale, ShieldCheck, Trash2 } from "lucide-react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { useAuthFetch } from "@/hooks/useAuthFetch";
import { useInventoryAccess } from "@/hooks/useInventoryAccess";
import { createTaxJurisdiction, createTaxRuleSet, createTaxVersion, deleteTaxJurisdiction, deleteTaxRuleSet, deleteTaxVersion, lifecycleCommand, updateTaxJurisdiction, updateTaxRuleSet, updateTaxVersion, validateVersion } from "./api";
import { useCatalogVariants, useTaxJurisdictions, useTaxPolicy, useTaxRuleSets, useTaxVersions } from "./hooks";
import type { LifecycleStatus, TaxJurisdiction, TaxRuleSet, TaxVersion } from "./contracts";
import { DeleteDialog } from "./DeleteDialog";
import { TaxJurisdictionEditor, TaxRuleSetEditor, TaxVersionEditor } from "./editors/TaxEditors";

const statusText: Record<LifecycleStatus, string> = { DRAFT: "مسودة", PENDING_APPROVAL: "بانتظار الاعتماد", PUBLISHED: "منشورة", SUPERSEDED: "مستبدلة", CANCELLED: "ملغاة" };
const statusClass: Record<LifecycleStatus, string> = { DRAFT: "bg-amber-50 text-amber-700 ring-amber-200", PENDING_APPROVAL: "bg-sky-50 text-sky-700 ring-sky-200", PUBLISHED: "bg-emerald-50 text-emerald-700 ring-emerald-200", SUPERSEDED: "bg-slate-100 text-slate-600 ring-slate-200", CANCELLED: "bg-rose-50 text-rose-700 ring-rose-200" };
function LoadMore({ visible, pending, onClick }: { visible: boolean; pending: boolean; onClick: () => void }) { return visible ? <button className="commercial-load-more" disabled={pending} onClick={onClick}>{pending ? "جاري التحميل..." : "تحميل المزيد"}</button> : null; }

export default function TaxManagement() {
  const authFetch = useAuthFetch(); const queryClient = useQueryClient(); const access = useInventoryAccess();
  const canManage = access.isCompanyAdmin || access.canAny("tax.manage"); const canApprove = access.isCompanyAdmin || access.canAny("tax.approve"); const catalogAvailable = access.isCompanyAdmin || access.canAny("catalog.read");
  const policy = useTaxPolicy(); const jurisdictions = useTaxJurisdictions(); const ruleSets = useTaxRuleSets(); const catalog = useCatalogVariants(catalogAvailable);
  const [selectedId, setSelectedId] = useState<number | null>(null); const versions = useTaxVersions(selectedId); const selected = ruleSets.items.find((row) => row.id === selectedId) ?? null;
  const [jurisdictionEditor, setJurisdictionEditor] = useState<TaxJurisdiction | "new" | null>(null); const [ruleSetEditor, setRuleSetEditor] = useState<TaxRuleSet | "new" | null>(null); const [versionEditor, setVersionEditor] = useState<TaxVersion | "new" | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<{ kind: "jurisdiction"; row: TaxJurisdiction } | { kind: "rule-set"; row: TaxRuleSet } | { kind: "version"; row: TaxVersion } | null>(null); const [reason, setReason] = useState("إجراء إداري من لوحة التحكم");
  useEffect(() => { if (!ruleSets.items.length) { setSelectedId(null); return; } if (!selectedId || !ruleSets.items.some((row) => row.id === selectedId)) setSelectedId(ruleSets.items[0].id); }, [ruleSets.items, selectedId]);
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["commercial-rules", "tax"] });
  const jurisdictionMutation = useMutation({ mutationFn: (input: Record<string, unknown>) => jurisdictionEditor === "new" ? createTaxJurisdiction(authFetch, input) : jurisdictionEditor ? updateTaxJurisdiction(authFetch, jurisdictionEditor.id, jurisdictionEditor.version, input) : Promise.reject(new Error("لم يتم تحديد النطاق.")), onSuccess: async () => { setJurisdictionEditor(null); toast.success("تم حفظ النطاق الضريبي."); await refresh(); } });
  const ruleSetMutation = useMutation({ mutationFn: (input: { code: string; name: string; description: string | null }) => ruleSetEditor === "new" ? createTaxRuleSet(authFetch, input) : ruleSetEditor ? updateTaxRuleSet(authFetch, ruleSetEditor.id, ruleSetEditor.version, input) : Promise.reject(new Error("لم يتم تحديد المجموعة.")), onSuccess: async () => { setRuleSetEditor(null); toast.success("تم حفظ مجموعة القواعد."); await refresh(); } });
  const versionMutation = useMutation({ mutationFn: (payload: Record<string, unknown>) => !selected ? Promise.reject(new Error("اختر مجموعة القواعد أولاً.")) : versionEditor === "new" ? createTaxVersion(authFetch, selected.id, selected.version, payload) : versionEditor ? updateTaxVersion(authFetch, versionEditor.id, versionEditor.version, payload) : Promise.reject(new Error("لم يتم تحديد النسخة.")), onSuccess: async () => { setVersionEditor(null); toast.success("تم حفظ النسخة الضريبية المسودة."); await refresh(); } });
  const deleteMutation = useMutation({ mutationFn: (why: string) => !deleteTarget ? Promise.reject(new Error("لم يتم تحديد العنصر.")) : deleteTarget.kind === "jurisdiction" ? deleteTaxJurisdiction(authFetch, deleteTarget.row.id, deleteTarget.row.version, why) : deleteTarget.kind === "rule-set" ? deleteTaxRuleSet(authFetch, deleteTarget.row.id, deleteTarget.row.version, why) : deleteTaxVersion(authFetch, deleteTarget.row.id, deleteTarget.row.version, why), onSuccess: async () => { setDeleteTarget(null); toast.success("تم تنفيذ الحذف."); await refresh(); } });
  const lifecycleMutation = useMutation({ mutationFn: ({ row, action }: { row: TaxVersion; action: "submit" | "publish" | "approve" | "cancel" }) => lifecycleCommand(authFetch, "taxation", row.id, action, row.version, reason.trim()), onSuccess: async () => { toast.success("تم تنفيذ إجراء الضريبة."); await refresh(); } });
  const validateMutation = useMutation({ mutationFn: (id: number) => validateVersion(authFetch, "taxation", id), onSuccess: () => toast.success("النسخة اجتازت التحقق البنيوي.") });
  const makerChecker = policy.data?.maker_checker_enabled === true; const lifecycleReasonValid = reason.trim().length >= 3;
  return <>
    <div className="commercial-tax-stack">
      <section className="commercial-rules-panel commercial-tax-jurisdictions"><div className="commercial-section-toolbar"><div><small>Tax Geography</small><h2>النطاقات الضريبية</h2></div>{canManage ? <button className="commercial-icon-action" onClick={() => setJurisdictionEditor("new")}><Plus className="h-4 w-4" /></button> : null}</div><div className="commercial-jurisdiction-strip custom-scrollbar">{jurisdictions.items.map((row) => <article className="commercial-jurisdiction-card" key={row.id}><div><strong>{row.name}</strong><small dir="ltr">{row.code}</small></div><span>{row.jurisdiction_type} · {row.country_code}</span><i data-active={row.is_active} />{canManage ? <div className="commercial-card-actions"><button onClick={() => setJurisdictionEditor(row)}><Pencil className="h-3.5 w-3.5" /></button><button onClick={() => setDeleteTarget({ kind: "jurisdiction", row })}><Trash2 className="h-3.5 w-3.5" /></button></div> : null}</article>)}</div><LoadMore visible={jurisdictions.hasNextPage === true} pending={jurisdictions.isFetchingNextPage} onClick={() => void jurisdictions.fetchNextPage()} /></section>
      <div className="commercial-rules-offers-grid"><section className="commercial-rules-panel commercial-rules-panel--rail"><div className="commercial-section-toolbar"><div><small>Rule Sets</small><h2>مجموعات القواعد</h2></div>{canManage ? <button className="commercial-icon-action" onClick={() => setRuleSetEditor("new")}><Plus className="h-4 w-4" /></button> : null}</div><div className="commercial-rules-list custom-scrollbar">{ruleSets.items.map((row) => <button key={row.id} onClick={() => setSelectedId(row.id)} className={`commercial-catalog-row ${selectedId === row.id ? "commercial-catalog-row--active" : ""}`}><span><strong>{row.name}</strong><small dir="ltr">{row.code}</small></span><em>v{row.version}</em></button>)}</div><LoadMore visible={ruleSets.hasNextPage === true} pending={ruleSets.isFetchingNextPage} onClick={() => void ruleSets.fetchNextPage()} /></section>
        <section className="commercial-rules-panel commercial-rules-panel--main">{!selected ? <p className="commercial-empty commercial-empty--large">اختر مجموعة ضريبية أو أنشئ واحدة.</p> : <><div className="commercial-detail-toolbar"><div className="commercial-detail-title"><span className="commercial-detail-icon"><Scale className="h-4 w-4" /></span><div><h2>{selected.name}</h2><p>{selected.description || "بدون وصف."}</p></div></div>{canManage ? <div className="commercial-toolbar-actions"><button className="commercial-soft-action" onClick={() => setRuleSetEditor(selected)}><Pencil className="h-3.5 w-3.5" /> تعديل</button><button className="commercial-soft-action commercial-soft-action--danger" onClick={() => setDeleteTarget({ kind: "rule-set", row: selected })}><Trash2 className="h-3.5 w-3.5" /> حذف</button><button className="commercial-primary-action" onClick={() => setVersionEditor("new")}><Plus className="h-3.5 w-3.5" /> نسخة مسودة</button></div> : null}</div>
          <div className="commercial-rules-version-list custom-scrollbar">{versions.items.map((row) => <article className="commercial-version-card" key={row.id}><div className="commercial-version-head"><div><div className="commercial-version-title"><strong>{row.price_mode === "INCLUSIVE" ? "شامل الضريبة" : "غير شامل"}</strong><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ring-1 ${statusClass[row.status]}`}>{statusText[row.status]}</span><small>r{row.revision}</small></div><div className="commercial-version-meta"><span>أولوية {row.priority}</span><span>{row.components.length} مكوّن</span><span>{row.scopes.length} نطاق</span></div></div><div className="commercial-toolbar-actions"><button className="commercial-soft-action" onClick={() => validateMutation.mutate(row.id)}>تحقق</button>{canManage && row.status === "DRAFT" ? <><button className="commercial-soft-action" onClick={() => setVersionEditor(row)}><Pencil className="h-3.5 w-3.5" /> تعديل</button><button className="commercial-soft-action commercial-soft-action--danger" onClick={() => setDeleteTarget({ kind: "version", row })}><Trash2 className="h-3.5 w-3.5" /> حذف</button><button className="commercial-primary-action" disabled={!lifecycleReasonValid || lifecycleMutation.isPending} onClick={() => lifecycleMutation.mutate({ row, action: makerChecker ? "submit" : "publish" })}>{makerChecker ? "إرسال للاعتماد" : "نشر"}</button></> : null}{canApprove && makerChecker && row.status === "PENDING_APPROVAL" ? <button className="commercial-success-action" disabled={!lifecycleReasonValid || lifecycleMutation.isPending} onClick={() => lifecycleMutation.mutate({ row, action: "approve" })}>اعتماد</button> : null}{canManage && ["DRAFT", "PENDING_APPROVAL"].includes(row.status) ? <button className="commercial-danger-action" disabled={!lifecycleReasonValid || lifecycleMutation.isPending} onClick={() => lifecycleMutation.mutate({ row, action: "cancel" })}>إلغاء</button> : null}</div></div><div className="commercial-component-grid">{row.components.map((component) => <div className="commercial-component-card" key={`${row.id}-${component.sequence}`}><span>#{component.sequence}</span><strong>{component.name}</strong><em dir="ltr">{component.rate}%</em><small>{component.basis_mode}</small></div>)}</div></article>)}</div>
          {canManage ? <div className="commercial-reason-bar"><ShieldCheck className="h-4 w-4" /><input value={reason} onChange={(e) => setReason(e.target.value)} maxLength={1000} aria-label="سبب الإجراء الإداري" /></div> : null}</>}</section></div>
    </div>
    <TaxJurisdictionEditor open={jurisdictionEditor !== null} jurisdiction={jurisdictionEditor === "new" ? null : jurisdictionEditor} jurisdictions={jurisdictions.items} pending={jurisdictionMutation.isPending} onClose={() => setJurisdictionEditor(null)} onSave={(input) => jurisdictionMutation.mutate(input)} />
    <TaxRuleSetEditor open={ruleSetEditor !== null} ruleSet={ruleSetEditor === "new" ? null : ruleSetEditor} pending={ruleSetMutation.isPending} onClose={() => setRuleSetEditor(null)} onSave={(input) => ruleSetMutation.mutate(input)} />
    <TaxVersionEditor open={versionEditor !== null} ruleSet={selected} version={versionEditor === "new" ? null : versionEditor} jurisdictions={jurisdictions.items} variants={catalog.items} catalogAvailable={catalogAvailable} hasMoreVariants={catalog.hasNextPage === true} loadingMoreVariants={catalog.isFetchingNextPage} onLoadMoreVariants={() => void catalog.fetchNextPage()} pending={versionMutation.isPending} onClose={() => setVersionEditor(null)} onSave={(payload) => versionMutation.mutate(payload)} />
    <DeleteDialog open={deleteTarget !== null} title={deleteTarget?.kind === "jurisdiction" ? "حذف النطاق الضريبي" : deleteTarget?.kind === "rule-set" ? "حذف مجموعة القواعد" : "حذف النسخة الضريبية"} message="سيطبق السيرفر قواعد الاعتماد والمراجع التاريخية؛ لا يمكن حذف ما هو مقفول أو مستخدم." pending={deleteMutation.isPending} onClose={() => setDeleteTarget(null)} onConfirm={(why) => deleteMutation.mutate(why)} />
  </>;
}
