"""initial_clean_start

Revision ID: 025110d60cff
Revises: 
Create Date: 2026-03-09 07:23:15.164930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025110d60cff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('name', name=op.f('uq_countries_name'))
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('can_allow_debt', sa.Boolean(), nullable=False),
    sa.Column('max_debt_limit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers')),
    sa.UniqueConstraint('username', name=op.f('uq_drivers_username'))
    )
    op.create_table('offer_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threshold_quantity', sa.Integer(), nullable=False),
    sa.Column('offer_type', sa.String(length=50), nullable=False),
    sa.Column('bonus_quantity', sa.Integer(), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_rules'))
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_name', sa.String(length=150), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=50), nullable=False),
    sa.Column('setting_value', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings')),
    sa.UniqueConstraint('setting_key', name=op.f('uq_system_settings_setting_key'))
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('current_mileage', sa.Integer(), nullable=False),
    sa.Column('next_oil_change', sa.Integer(), nullable=True),
    sa.Column('license_expiry_date', sa.Date(), nullable=True),
    sa.Column('maintenance_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('plate_number', name=op.f('uq_vehicles_plate_number'))
    )
    op.create_table('governorates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_governorates_country_id_countries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_governorates'))
    )
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_name', sa.String(length=200), nullable=False),
    sa.Column('flavor', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('packs_per_carton', sa.Integer(), nullable=False),
    sa.Column('price_per_carton', sa.Float(), nullable=False),
    sa.Column('price_per_pack', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_max_samples_per_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('sku', name=op.f('uq_product_variants_sku'))
    )
    op.create_table('work_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_latitude', sa.Float(), nullable=True),
    sa.Column('start_longitude', sa.Float(), nullable=True),
    sa.Column('is_authorized_to_sell', sa.Boolean(), nullable=False),
    sa.Column('break_start_time', sa.DateTime(), nullable=True),
    sa.Column('break_end_time', sa.DateTime(), nullable=True),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_work_sessions_driver_id_drivers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_sessions'))
    )
    op.create_table('session_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_session_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('starting_quantity', sa.Integer(), nullable=False),
    sa.Column('current_remaining_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_session_inventory_product_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], name=op.f('fk_session_inventory_work_session_id_work_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_inventory'))
    )
    op.create_table('vehicle_loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_vehicle_loads_product_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_vehicle_loads_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_loads'))
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('governorate_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('schedule_frequency', sa.String(length=50), nullable=True),
    sa.Column('visit_day', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('custom_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['governorate_id'], ['governorates.id'], name=op.f('fk_zones_governorate_id_governorates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones'))
    )
    op.create_table('dispatch_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('work_session_id', sa.Integer(), nullable=True),
    sa.Column('dispatch_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_dispatch_routes_driver_id_drivers')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_dispatch_routes_vehicle_id_vehicles')),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], name=op.f('fk_dispatch_routes_work_session_id_work_sessions')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_dispatch_routes_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatch_routes'))
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('max_debt_limit', sa.Float(), nullable=False),
    sa.Column('added_by_driver_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('location_link', sa.String(length=500), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_driver_id'], ['drivers.id'], name=op.f('fk_shops_added_by_driver_id_drivers')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_shops_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops'))
    )
    op.create_table('shortage_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_shortage_orders_driver_id_drivers')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_shortage_orders_product_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shortage_orders_shop_id_shops')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_shortage_orders_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shortage_orders'))
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('work_session_id', sa.Integer(), nullable=True),
    sa.Column('visit_timestamp', sa.DateTime(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('amount_before_tax_and_discount', sa.Float(), nullable=True),
    sa.Column('discount_applied', sa.Float(), nullable=True),
    sa.Column('tax_percentage_applied', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('final_amount_due', sa.Float(), nullable=True),
    sa.Column('cash_collected', sa.Float(), nullable=True),
    sa.Column('debt_paid', sa.Float(), nullable=False),
    sa.Column('no_sale_reason', sa.String(length=200), nullable=True),
    sa.Column('shop_balance_before', sa.Float(), nullable=True),
    sa.Column('shop_balance_after', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tax_qr_code', sa.String(length=500), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_visits_driver_id_drivers')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_visits_shop_id_shops')),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], name=op.f('fk_visits_work_session_id_work_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visits'))
    )
    op.create_table('visit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('bonus_quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_unit_at_sale', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('sample_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_visit_items_product_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('fk_visit_items_visit_id_visits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visit_items'))
    )
    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_items_product_variant_id'), ['product_variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_items_visit_id'), ['visit_id'], unique=False)

    op.create_table('visit_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('return_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_visit_returns_product_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('fk_visit_returns_visit_id_visits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visit_returns'))
    )
    with op.batch_alter_table('visit_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_returns_product_variant_id'), ['product_variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_returns_visit_id'), ['visit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_returns_visit_id'))
        batch_op.drop_index(batch_op.f('ix_visit_returns_product_variant_id'))

    op.drop_table('visit_returns')
    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_items_visit_id'))
        batch_op.drop_index(batch_op.f('ix_visit_items_product_variant_id'))

    op.drop_table('visit_items')
    op.drop_table('visits')
    op.drop_table('shortage_orders')
    op.drop_table('shops')
    op.drop_table('dispatch_routes')
    op.drop_table('zones')
    op.drop_table('vehicle_loads')
    op.drop_table('session_inventory')
    op.drop_table('work_sessions')
    op.drop_table('product_variants')
    op.drop_table('governorates')
    op.drop_table('vehicles')
    op.drop_table('system_settings')
    op.drop_table('products')
    op.drop_table('offer_rules')
    op.drop_table('drivers')
    op.drop_table('countries')
    # ### end Alembic commands ###
