"""Add debt_paid column to Visit table

Revision ID: 05191d866bd2
Revises: 6140bd904abf
Create Date: 2025-04-15 22:24:11.319874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05191d866bd2'
down_revision = '6140bd904abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debt_paid', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_column('debt_paid')

    # ### end Alembic commands ###
