"""Added Indexes and Unique Constraints for DBA optimization

Revision ID: 13f264dbc698
Revises: 68f9f9114ef8
Create Date: 2026-03-24 06:20:12.687125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f264dbc698'
down_revision = '68f9f9114ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_routes_dispatch_date'), ['dispatch_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_routes_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_routes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_routes_vehicle_id'), ['vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_routes_work_session_id'), ['work_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_routes_zone_id'), ['zone_id'], unique=False)

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variants_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('session_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_inventory_product_variant_id'), ['product_variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_inventory_work_session_id'), ['work_session_id'], unique=False)
        batch_op.create_unique_constraint('uq_session_variant_inv', ['work_session_id', 'product_variant_id'])

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shops_zone_id'), ['zone_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_shops_zone_id_zones'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_shops_zone_id_zones'), 'zones', ['zone_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('vehicle_loads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_loads_vehicle_id'), ['vehicle_id'], unique=False)
        batch_op.create_unique_constraint('uq_vehicle_variant_load', ['vehicle_id', 'product_variant_id'])

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_visit_timestamp'), ['visit_timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_visit_timestamp'))
        batch_op.drop_index(batch_op.f('ix_visits_status'))

    with op.batch_alter_table('vehicle_loads', schema=None) as batch_op:
        batch_op.drop_constraint('uq_vehicle_variant_load', type_='unique')
        batch_op.drop_index(batch_op.f('ix_vehicle_loads_vehicle_id'))

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shops_zone_id_zones'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_shops_zone_id_zones'), 'zones', ['zone_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_shops_zone_id'))

    with op.batch_alter_table('session_inventory', schema=None) as batch_op:
        batch_op.drop_constraint('uq_session_variant_inv', type_='unique')
        batch_op.drop_index(batch_op.f('ix_session_inventory_work_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_inventory_product_variant_id'))

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_is_active'))

    with op.batch_alter_table('dispatch_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_routes_zone_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_routes_work_session_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_routes_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_routes_status'))
        batch_op.drop_index(batch_op.f('ix_dispatch_routes_driver_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_routes_dispatch_date'))

    # ### end Alembic commands ###
