""", , ,  table

Revision ID: 22d55e0e0173
Revises: 4f59a472a4aa
Create Date: 2026-04-24 15:25:25.094533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d55e0e0173'
down_revision = '4f59a472a4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_warehouse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_main_warehouse_last_updated'), ['last_updated'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_warehouse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_warehouse_last_updated'))

    # ### end Alembic commands ###
