"""Add ImportLog table

Revision ID: 23b70a07cc17
Revises: dc9d12aaab29
Create Date: 2026-03-13 02:45:54.800789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b70a07cc17'
down_revision = 'dc9d12aaab29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['drivers.id'], name=op.f('fk_import_logs_admin_id_drivers')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_import_logs_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_logs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_logs')
    # ### end Alembic commands ###
