"""convert floats to numerics and add audit logs

Revision ID: 2ad46f6dd781
Revises: fe7aa8fcb8e5
Create Date: 2026-03-21 03:08:47.660760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad46f6dd781'
down_revision = 'fe7aa8fcb8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['drivers.id'], name=op.f('fk_system_audit_logs_admin_id_drivers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_audit_logs'))
    )
    with op.batch_alter_table('system_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_audit_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_audit_logs_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_audit_logs_target_id'), ['target_id'], unique=False)

    op.create_table('work_break_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_session_id', sa.Integer(), nullable=False),
    sa.Column('break_start', sa.DateTime(), nullable=False),
    sa.Column('break_end', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], name=op.f('fk_work_break_logs_work_session_id_work_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_break_logs'))
    )
    with op.batch_alter_table('work_break_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_break_logs_work_session_id'), ['work_session_id'], unique=False)

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.alter_column('max_debt_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.alter_column('price_per_carton',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('price_per_pack',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.alter_column('current_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('max_debt_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('shortage_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shortage_requests_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shortage_requests_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shortage_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shortage_requests_zone_id'), ['zone_id'], unique=False)

    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.alter_column('price_per_unit_at_sale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.alter_column('amount_before_tax_and_discount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('discount_applied',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('tax_percentage_applied',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('final_amount_due',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('cash_collected',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('debt_paid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('shop_balance_before',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('shop_balance_after',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_visits_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_work_session_id'), ['work_session_id'], unique=False)

    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_sessions_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_sessions_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_sessions_is_settled'), ['is_settled'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_sessions_session_date'), ['session_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_sessions_session_date'))
        batch_op.drop_index(batch_op.f('ix_work_sessions_is_settled'))
        batch_op.drop_index(batch_op.f('ix_work_sessions_end_time'))
        batch_op.drop_index(batch_op.f('ix_work_sessions_driver_id'))

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_work_session_id'))
        batch_op.drop_index(batch_op.f('ix_visits_shop_id'))
        batch_op.drop_index(batch_op.f('ix_visits_outcome'))
        batch_op.drop_index(batch_op.f('ix_visits_driver_id'))
        batch_op.alter_column('shop_balance_after',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('shop_balance_before',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('debt_paid',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('cash_collected',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('final_amount_due',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('tax_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('tax_percentage_applied',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('discount_applied',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('amount_before_tax_and_discount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('price_per_unit_at_sale',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('shortage_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shortage_requests_zone_id'))
        batch_op.drop_index(batch_op.f('ix_shortage_requests_status'))
        batch_op.drop_index(batch_op.f('ix_shortage_requests_shop_id'))
        batch_op.drop_index(batch_op.f('ix_shortage_requests_driver_id'))

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.alter_column('max_debt_limit',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('current_balance',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.alter_column('price_per_pack',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('price_per_carton',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.alter_column('max_debt_limit',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('work_break_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_break_logs_work_session_id'))

    op.drop_table('work_break_logs')
    with op.batch_alter_table('system_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_audit_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_system_audit_logs_admin_id'))
        batch_op.drop_index(batch_op.f('ix_system_audit_logs_action_type'))

    op.drop_table('system_audit_logs')
    # ### end Alembic commands ###
