"""Set final NOT NULL constraints

Revision ID: 30a5838c32a2
Revises: 05191d866bd2
Create Date: 2025-04-15 22:50:42.018103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a5838c32a2'
down_revision = '05191d866bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- الخطوة 1: تعبئة القيم الافتراضية أولاً ---
    try:
        bind = op.get_bind()
        op.execute(f"UPDATE drivers SET default_starting_cartons = 61 WHERE default_starting_cartons IS NULL")
        op.execute(f"UPDATE work_sessions SET starting_cartons = 61, current_remaining_cartons = 61 WHERE starting_cartons IS NULL")
        op.execute(f"UPDATE visits SET debt_paid = 0.0 WHERE debt_paid IS NULL")
    except Exception as e:
        print(f"An error occurred during UPDATE: {e}")
        raise e
    # --- نهاية الخطوة 1 ---

    # --- الخطوة 2: تغيير الأعمدة لتصبح NOT NULL ---
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.alter_column('default_starting_cartons',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='61') # <-- تأكد من هذا الجزء لـ drivers

    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.alter_column('starting_cartons',
               existing_type=sa.INTEGER(),
               nullable=False) # <-- تأكد من هذا الجزء لـ work_sessions
        batch_op.alter_column('current_remaining_cartons',
               existing_type=sa.INTEGER(),
               nullable=False) # <-- تأكد من هذا الجزء لـ work_sessions

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.alter_column('debt_paid',
               existing_type=sa.FLOAT(),
               nullable=False,
               server_default='0.0') # <-- تأكد من هذا الجزء لـ visits (مع server_default)

    # --- نهاية الخطوة 2 ---

    # ### end Alembic commands ###
    # pass # يمكنك ترك pass إذا كانت موجودة أو حذفها


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.alter_column('debt_paid',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
