"""fix timezone consistency and shortage FK

Revision ID: 4b9f70a7efba
Revises: 6fedcef2ca25
Create Date: 2026-03-29 01:02:38.536068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b9f70a7efba'
down_revision = '6fedcef2ca25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_ledgers', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('inventory_transfers', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('shortage_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_variant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_shortage_requests_product_variant_id'), ['product_variant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_shortage_requests_product_variant_id_product_variants'), 'product_variants', ['product_variant_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shortage_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_shortage_requests_product_variant_id_product_variants'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_shortage_requests_product_variant_id'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('product_variant_id')

    with op.batch_alter_table('inventory_transfers', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('inventory_ledgers', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
