"""Add MainWarehouse, DamagedItemLog, WarehouseLedger,  table

Revision ID: 4f59a472a4aa
Revises: 5d58c37e9ec6
Create Date: 2026-04-24 13:40:34.379794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f59a472a4aa'
down_revision = '5d58c37e9ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_warehouse',
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('available_quantity_packs', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity_packs', sa.Integer(), nullable=False),
    sa.Column('min_threshold_packs', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_main_warehouse_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_variant_id', name=op.f('pk_main_warehouse'))
    )
    op.create_table('warehouse_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity_packs', sa.Integer(), nullable=False),
    sa.Column('balance_after_packs', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['drivers.id'], name=op.f('fk_warehouse_ledger_admin_id_drivers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_warehouse_ledger_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse_ledger'))
    )
    with op.batch_alter_table('warehouse_ledger', schema=None) as batch_op:
        batch_op.create_index('idx_ledger_variant_created', ['product_variant_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_ledger_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_ledger_transaction_type'), ['transaction_type'], unique=False)

    op.create_table('damaged_items_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity_packs', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(length=50), nullable=False),
    sa.Column('source_driver_id', sa.Integer(), nullable=True),
    sa.Column('source_visit_id', sa.Integer(), nullable=True),
    sa.Column('receiving_admin_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_damaged_items_log_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receiving_admin_id'], ['drivers.id'], name=op.f('fk_damaged_items_log_receiving_admin_id_drivers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_driver_id'], ['drivers.id'], name=op.f('fk_damaged_items_log_source_driver_id_drivers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_visit_id'], ['visits.id'], name=op.f('fk_damaged_items_log_source_visit_id_visits'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_damaged_items_log'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('damaged_items_log')
    with op.batch_alter_table('warehouse_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_ledger_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_warehouse_ledger_reference_id'))
        batch_op.drop_index('idx_ledger_variant_created')

    op.drop_table('warehouse_ledger')
    op.drop_table('main_warehouse')
    # ### end Alembic commands ###
