"""Add work_session_id and relationship to Visit

Revision ID: 54189a8a8d1b
Revises: a1225bdfc178
Create Date: 2025-04-18 01:16:02.685809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54189a8a8d1b'
down_revision = 'a1225bdfc178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'work_sessions', ['work_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('work_session_id')

    # ### end Alembic commands ###
