"""mof  table

Revision ID: 57a83a70f034
Revises: 22d55e0e0173
Create Date: 2026-04-24 15:37:19.287926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a83a70f034'
down_revision = '22d55e0e0173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('damaged_items_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_damaged_items_log_receiving_admin_id_drivers'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_damaged_items_log_receiving_admin_id_drivers'), 'drivers', ['receiving_admin_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('offer_rules', schema=None) as batch_op:
        batch_op.alter_column('discount_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer_rules', schema=None) as batch_op:
        batch_op.alter_column('discount_value',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('damaged_items_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_damaged_items_log_receiving_admin_id_drivers'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_damaged_items_log_receiving_admin_id_drivers'), 'drivers', ['receiving_admin_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
