"""add_returns_and_samples

Revision ID: 584a5e377153
Revises: 
Create Date: 2026-03-05 01:35:25.316185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584a5e377153'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity_cartons', sa.Integer(), nullable=False),
    sa.Column('quantity_packs', sa.Integer(), nullable=False),
    sa.Column('return_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_visit_returns_product_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('fk_visit_returns_visit_id_visits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visit_returns'))
    )
    with op.batch_alter_table('visit_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_returns_product_variant_id'), ['product_variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_returns_visit_id'), ['visit_id'], unique=False)

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_max_samples_per_day', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_cartons', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('sample_packs', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_emergency', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_column('is_emergency')

    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.drop_column('sample_packs')
        batch_op.drop_column('sample_cartons')

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_column('default_max_samples_per_day')

    with op.batch_alter_table('visit_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_returns_visit_id'))
        batch_op.drop_index(batch_op.f('ix_visit_returns_product_variant_id'))

    op.drop_table('visit_returns')
    # ### end Alembic commands ###
