"""Add notes for InventoryTransfer table

Revision ID: 5d58c37e9ec6
Revises: b304277404ce
Create Date: 2026-04-24 02:11:55.019805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d58c37e9ec6'
down_revision = 'b304277404ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transfers', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
