"""allow orphan visits

Revision ID: 68f9f9114ef8
Revises: bf91133eff61
Create Date: 2026-03-21 11:07:00.513727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f9f9114ef8'
down_revision = 'bf91133eff61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.alter_column('driver_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.alter_column('driver_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
