"""Add remaining packs column to WorkSession

Revision ID: 718a04b4d5d1
Revises: 54189a8a8d1b
Create Date: 2025-04-18 09:12:09.594384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718a04b4d5d1'
down_revision = '54189a8a8d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_drivers_username'), ['username'])

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_product_variants_sku'), ['sku'])

    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_remaining_packs', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.drop_column('current_remaining_packs')

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_product_variants_sku'), type_='unique')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_drivers_username'), type_='unique')

    # ### end Alembic commands ###
