"""empty message

Revision ID: 8b67c2253bf4
Revises: 13f264dbc698
Create Date: 2026-03-24 08:29:07.904093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b67c2253bf4'
down_revision = '13f264dbc698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packs_quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.drop_column('packs_quantity')

    # ### end Alembic commands ###
