"""Add ShortageRequest table

Revision ID: 8f62fe6d8644
Revises: 025110d60cff
Create Date: 2026-03-12 08:03:01.762147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f62fe6d8644'
down_revision = '025110d60cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortage_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('wait_time', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_shortage_requests_driver_id_drivers')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shortage_requests_shop_id_shops')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_shortage_requests_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shortage_requests'))
    )
    op.drop_table('shortage_orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortage_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_variant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fulfilled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_shortage_orders_driver_id_drivers')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_shortage_orders_product_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shortage_orders_shop_id_shops')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_shortage_orders_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shortage_orders'))
    )
    op.drop_table('shortage_requests')
    # ### end Alembic commands ###
