"""Add start coordinates to WorkSession

Revision ID: a1225bdfc178
Revises: 30a5838c32a2
Create Date: 2025-04-18 00:21:47.052308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1225bdfc178'
down_revision = '30a5838c32a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('start_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.drop_column('start_longitude')
        batch_op.drop_column('start_latitude')

    # ### end Alembic commands ###
