"""Add net_transfers column

Revision ID: a451c70af914
Revises: 6d88d1d1ccf1
Create Date: 2026-05-03 15:33:21.848036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a451c70af914'
down_revision = '6d88d1d1ccf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_transfers', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_inventory', schema=None) as batch_op:
        batch_op.drop_column('net_transfers')

    # ### end Alembic commands ###
