"""Add is_cancelled to VisitItem and VisitReturn

Revision ID: b304277404ce
Revises: f3d946dbb859
Create Date: 2026-04-21 12:42:05.951365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b304277404ce'
down_revision = 'f3d946dbb859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('visit_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_returns', schema=None) as batch_op:
        batch_op.drop_column('is_cancelled')

    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.drop_column('is_cancelled')

    # ### end Alembic commands ###
