"""Add packs quantity to returns and samples

Revision ID: b9562b296cc1
Revises: 4b9f70a7efba
Create Date: 2026-04-12 16:19:50.436960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9562b296cc1'
down_revision = '4b9f70a7efba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_packs_quantity', sa.Integer(), nullable=False))

    with op.batch_alter_table('visit_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packs_quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_returns', schema=None) as batch_op:
        batch_op.drop_column('packs_quantity')

    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.drop_column('sample_packs_quantity')

    # ### end Alembic commands ###
