"""add restrict constraints to foreign keys

Revision ID: bf91133eff61
Revises: 2ad46f6dd781
Create Date: 2026-03-21 03:26:33.178984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf91133eff61'
down_revision = '2ad46f6dd781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_visit_items_product_variant_id_product_variants'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_visit_items_product_variant_id_product_variants'), 'product_variants', ['product_variant_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('visit_returns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_visit_returns_product_variant_id_product_variants'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_visit_returns_product_variant_id_product_variants'), 'product_variants', ['product_variant_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_returns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_visit_returns_product_variant_id_product_variants'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_visit_returns_product_variant_id_product_variants'), 'product_variants', ['product_variant_id'], ['id'])

    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_visit_items_product_variant_id_product_variants'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_visit_items_product_variant_id_product_variants'), 'product_variants', ['product_variant_id'], ['id'])

    # ### end Alembic commands ###
