"""Add ShortageRequest table1

Revision ID: dc9d12aaab29
Revises: 8f62fe6d8644
Create Date: 2026-03-12 08:11:56.441335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9d12aaab29'
down_revision = '8f62fe6d8644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.alter_column('governorate_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.alter_column('governorate_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
