"""add sample_reason to visit_item

Revision ID: f3d946dbb859
Revises: b9562b296cc1
Create Date: 2026-04-14 21:10:51.266687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d946dbb859'
down_revision = 'b9562b296cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.drop_column('sample_reason')

    # ### end Alembic commands ###
