"""add inventory ledger table

Revision ID: fe7aa8fcb8e5
Revises: 23b70a07cc17
Create Date: 2026-03-20 01:19:57.683219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7aa8fcb8e5'
down_revision = '23b70a07cc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_session_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['drivers.id'], name=op.f('fk_inventory_ledgers_admin_id_drivers')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_inventory_ledgers_driver_id_drivers')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_inventory_ledgers_product_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_inventory_ledgers_vehicle_id_vehicles')),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], name=op.f('fk_inventory_ledgers_work_session_id_work_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_ledgers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_ledgers')
    # ### end Alembic commands ###
