"""Phase 1 DB schema hardening constraints and precision

Revision ID: 17bb3dec2056
Revises: 
Create Date: 2026-07-26 05:31:18.325528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17bb3dec2056'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_active_route_per_driver', 'dispatch_routes', ['driver_id'], unique=True, postgresql_where=sa.text("status IN ('active', 'waiting')"))
    op.create_index('uq_active_route_per_vehicle', 'dispatch_routes', ['vehicle_id'], unique=True, postgresql_where=sa.text("status IN ('active', 'waiting')"))
    op.create_index('uq_active_route_per_zone', 'dispatch_routes', ['zone_id'], unique=True, postgresql_where=sa.text("status IN ('active', 'waiting', 'postponed')"))
    op.create_unique_constraint('uq_governorate_name_per_country', 'governorates', ['name', 'country_id'])
    op.drop_constraint(op.f('fk_import_logs_admin_id_drivers'), 'import_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_import_logs_admin_id_drivers'), 'import_logs', 'drivers', ['admin_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_inventory_ledgers_work_session_id'), 'inventory_ledgers', ['work_session_id'], unique=False)
    op.drop_constraint(op.f('fk_inventory_transfers_work_session_id_work_sessions'), 'inventory_transfers', type_='foreignkey')
    op.drop_constraint(op.f('fk_inventory_transfers_product_variant_id_product_variants'), 'inventory_transfers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inventory_transfers_product_variant_id_product_variants'), 'inventory_transfers', 'product_variants', ['product_variant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_inventory_transfers_work_session_id_work_sessions'), 'inventory_transfers', 'work_sessions', ['work_session_id'], ['id'], ondelete='RESTRICT')
    op.create_unique_constraint(op.f('uq_products_base_name'), 'products', ['base_name'])
    op.drop_constraint(op.f('fk_system_audit_logs_admin_id_drivers'), 'system_audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_system_audit_logs_admin_id_drivers'), 'system_audit_logs', 'drivers', ['admin_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_visit_returns_visit_id_visits'), 'visit_returns', type_='foreignkey')
    op.create_foreign_key(op.f('fk_visit_returns_visit_id_visits'), 'visit_returns', 'visits', ['visit_id'], ['id'], ondelete='CASCADE')
    op.alter_column('visits', 'cash_collected',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.create_index('ix_visit_session_outcome', 'visits', ['work_session_id', 'outcome'], unique=False)
    op.create_index('ix_visit_shop_timestamp', 'visits', ['shop_id', 'visit_timestamp'], unique=False)
    op.add_column('warehouse_ledger', sa.Column('balance_before_packs', sa.Integer(), nullable=False, server_default='0'))
    op.create_index('uq_ledger_supplier_ref', 'warehouse_ledger', ['reference_id'], unique=True, postgresql_where=sa.text("transaction_type IN ('INBOUND_SUPPLIER', 'INBOUND_CORRECTION') AND reference_id IS NOT NULL AND reference_id != 'بدون فاتورة'"))
    op.create_index('ix_ws_driver_unsettled', 'work_sessions', ['driver_id', 'is_settled', 'end_time'], unique=False)
    op.create_unique_constraint('uq_zone_name_per_governorate', 'zones', ['name', 'governorate_id'])
    op.drop_constraint(op.f('fk_zones_governorate_id_governorates'), 'zones', type_='foreignkey')
    op.create_foreign_key(op.f('fk_zones_governorate_id_governorates'), 'zones', 'governorates', ['governorate_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_zones_governorate_id_governorates'), 'zones', type_='foreignkey')
    op.create_foreign_key(op.f('fk_zones_governorate_id_governorates'), 'zones', 'governorates', ['governorate_id'], ['id'])
    op.drop_constraint('uq_zone_name_per_governorate', 'zones', type_='unique')
    op.drop_index('ix_ws_driver_unsettled', table_name='work_sessions')
    op.drop_index('uq_ledger_supplier_ref', table_name='warehouse_ledger', postgresql_where=sa.text("transaction_type IN ('INBOUND_SUPPLIER', 'INBOUND_CORRECTION') AND reference_id IS NOT NULL AND reference_id != 'بدون فاتورة'"))
    op.drop_column('warehouse_ledger', 'balance_before_packs')
    op.drop_index('ix_visit_shop_timestamp', table_name='visits')
    op.drop_index('ix_visit_session_outcome', table_name='visits')
    op.alter_column('visits', 'cash_collected',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.drop_constraint(op.f('fk_visit_returns_visit_id_visits'), 'visit_returns', type_='foreignkey')
    op.create_foreign_key(op.f('fk_visit_returns_visit_id_visits'), 'visit_returns', 'visits', ['visit_id'], ['id'])
    op.drop_constraint(op.f('fk_system_audit_logs_admin_id_drivers'), 'system_audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_system_audit_logs_admin_id_drivers'), 'system_audit_logs', 'drivers', ['admin_id'], ['id'])
    op.drop_constraint(op.f('uq_products_base_name'), 'products', type_='unique')
    op.drop_constraint(op.f('fk_inventory_transfers_work_session_id_work_sessions'), 'inventory_transfers', type_='foreignkey')
    op.drop_constraint(op.f('fk_inventory_transfers_product_variant_id_product_variants'), 'inventory_transfers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inventory_transfers_product_variant_id_product_variants'), 'inventory_transfers', 'product_variants', ['product_variant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_inventory_transfers_work_session_id_work_sessions'), 'inventory_transfers', 'work_sessions', ['work_session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_inventory_ledgers_work_session_id'), table_name='inventory_ledgers')
    op.drop_constraint(op.f('fk_import_logs_admin_id_drivers'), 'import_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_import_logs_admin_id_drivers'), 'import_logs', 'drivers', ['admin_id'], ['id'])
    op.drop_constraint('uq_governorate_name_per_country', 'governorates', type_='unique')
    op.drop_index('uq_active_route_per_zone', table_name='dispatch_routes', postgresql_where=sa.text("status IN ('active', 'waiting', 'postponed')"))
    op.drop_index('uq_active_route_per_vehicle', table_name='dispatch_routes', postgresql_where=sa.text("status IN ('active', 'waiting')"))
    op.drop_index('uq_active_route_per_driver', table_name='dispatch_routes', postgresql_where=sa.text("status IN ('active', 'waiting')"))
    # ### end Alembic commands ###
