"""SaaS_Core_Stage_1_Schema_Foundation_Final

Revision ID: 2462c463c46b
Revises: 2b482e1ffbb9
Create Date: 2026-09-02 02:29:56.773678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2462c463c46b'
down_revision: Union[str, Sequence[str], None] = '2b482e1ffbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('company_code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("subscription_status IN ('active', 'suspended', 'expired', 'trial')", name=op.f('ck_companies_chk_company_sub_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_company_code'), 'companies', ['company_code'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('platform_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_admins')),
    sa.UniqueConstraint('username', name=op.f('uq_platform_admins_username'))
    )
    op.create_table('uom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uom')),
    sa.UniqueConstraint('code', name=op.f('uq_uom_code')),
    sa.UniqueConstraint('name', name=op.f('uq_uom_name'))
    )
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('branch_code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_branches_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('company_id', 'branch_code', name='uq_company_branch_code'),
    sa.UniqueConstraint('company_id', 'id', name='uq_branches_company_id')
    )
    op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_roles_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('company_id', 'id', name='uq_roles_company_id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_company_role_name')
    )
    op.create_index(op.f('ix_roles_company_id'), 'roles', ['company_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('uom_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('from_uom_id', sa.Integer(), nullable=False),
    sa.Column('to_uom_id', sa.Integer(), nullable=False),
    sa.Column('conversion_factor', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_uom_conversions_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_uom_id'], ['uom.id'], name=op.f('fk_uom_conversions_from_uom_id_uom'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_uom_conversions_product_variant_id_product_variants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_uom_id'], ['uom.id'], name=op.f('fk_uom_conversions_to_uom_id_uom'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uom_conversions')),
    sa.UniqueConstraint('company_id', 'product_variant_id', 'from_uom_id', 'to_uom_id', name='uq_uom_conversion')
    )
    op.create_index(op.f('ix_uom_conversions_company_id'), 'uom_conversions', ['company_id'], unique=False)
    op.add_column('dispatch_routes', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('uq_active_route_per_driver'), table_name='dispatch_routes', postgresql_where="((status)::text = ANY ((ARRAY['active'::character varying, 'waiting'::character varying, 'postponed'::character varying])::text[]))")
    op.create_index('uq_active_route_per_driver', 'dispatch_routes', ['company_id', 'driver_id'], unique=True, postgresql_where=sa.text("status IN ('active', 'waiting', 'postponed')"))
    op.drop_index(op.f('uq_active_route_per_vehicle'), table_name='dispatch_routes', postgresql_where="((status)::text = ANY ((ARRAY['active'::character varying, 'waiting'::character varying, 'postponed'::character varying])::text[]))")
    op.create_index('uq_active_route_per_vehicle', 'dispatch_routes', ['company_id', 'vehicle_id'], unique=True, postgresql_where=sa.text("status IN ('active', 'waiting', 'postponed')"))
    op.drop_index(op.f('uq_active_route_per_zone'), table_name='dispatch_routes', postgresql_where="((status)::text = ANY ((ARRAY['active'::character varying, 'waiting'::character varying, 'postponed'::character varying])::text[]))")
    op.create_index('uq_active_route_per_zone', 'dispatch_routes', ['company_id', 'zone_id'], unique=True, postgresql_where=sa.text("status IN ('active', 'waiting', 'postponed')"))
    op.create_index(op.f('ix_dispatch_routes_company_id'), 'dispatch_routes', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_dispatch_routes_company_id_companies'), 'dispatch_routes', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('drivers', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_drivers_username'), 'drivers', type_='unique')
    op.create_index(op.f('ix_drivers_company_id'), 'drivers', ['company_id'], unique=False)
    op.create_unique_constraint('uq_company_username', 'drivers', ['company_id', 'username'])
    op.create_unique_constraint('uq_drivers_company_id', 'drivers', ['company_id', 'id'])
    op.create_foreign_key(op.f('fk_drivers_company_id_companies'), 'drivers', 'companies', ['company_id'], ['id'], ondelete='CASCADE')

    # +++ (QA FIX) نقل إنشاء جدولي RBAC إلى بعد إنشاء uq_drivers_company_id لتفجير قيد FK المركب +++
    op.create_table('user_location_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'driver_id'], ['drivers.company_id', 'drivers.id'], name=op.f('fk_user_location_access_company_id_drivers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id', 'role_id'], ['roles.company_id', 'roles.id'], name=op.f('fk_user_location_access_company_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_location_access')),
    sa.UniqueConstraint('company_id', 'driver_id', 'location_id', 'role_id', name='uq_user_loc_access_tenant')
    )
    op.create_index(op.f('ix_user_location_access_company_id'), 'user_location_access', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_location_access_driver_id'), 'user_location_access', ['driver_id'], unique=False)
    op.create_index(op.f('ix_user_location_access_location_id'), 'user_location_access', ['location_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id', 'driver_id'], ['drivers.company_id', 'drivers.id'], name=op.f('fk_user_roles_company_id_drivers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id', 'role_id'], ['roles.company_id', 'roles.id'], name=op.f('fk_user_roles_company_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('company_id', 'driver_id', 'role_id', name='uq_user_role_tenant')
    )
    op.create_index(op.f('ix_user_roles_company_id'), 'user_roles', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_roles_driver_id'), 'user_roles', ['driver_id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.add_column('import_logs', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_import_logs_company_id'), 'import_logs', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_import_logs_company_id_companies'), 'import_logs', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('inventory_transfers', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('uq_pending_transfer'), table_name='inventory_transfers', postgresql_where="((status)::text = 'pending'::text)")
    op.create_index('uq_pending_transfer', 'inventory_transfers', ['company_id', 'work_session_id', 'product_variant_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_index(op.f('ix_inventory_transfers_company_id'), 'inventory_transfers', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_inventory_transfers_company_id_companies'), 'inventory_transfers', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('offer_rules', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_offer_rules_company_id'), 'offer_rules', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_offer_rules_company_id_companies'), 'offer_rules', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('product_variants', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('product_variants', sa.Column('base_uom_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_product_variants_sku'), 'product_variants', type_='unique')
    op.create_index(op.f('ix_product_variants_company_id'), 'product_variants', ['company_id'], unique=False)
    op.create_unique_constraint('uq_company_sku', 'product_variants', ['company_id', 'sku'])
    op.create_foreign_key(op.f('fk_product_variants_company_id_companies'), 'product_variants', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_product_variants_base_uom_id_uom'), 'product_variants', 'uom', ['base_uom_id'], ['id'], ondelete='RESTRICT')
    op.add_column('products', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_products_base_name'), 'products', type_='unique')
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_unique_constraint('uq_company_base_name', 'products', ['company_id', 'base_name'])
    op.create_foreign_key(op.f('fk_products_company_id_companies'), 'products', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('session_inventory', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_session_inventory_company_id'), 'session_inventory', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_session_inventory_company_id_companies'), 'session_inventory', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('shops', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shops_company_id'), 'shops', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_shops_company_id_companies'), 'shops', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('shortage_requests', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shortage_requests_company_id'), 'shortage_requests', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_shortage_requests_company_id_companies'), 'shortage_requests', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('system_audit_logs', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_system_audit_logs_company_id'), 'system_audit_logs', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_system_audit_logs_company_id_companies'), 'system_audit_logs', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('system_settings', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_system_settings_setting_key'), 'system_settings', type_='unique')
    op.create_index(op.f('ix_system_settings_company_id'), 'system_settings', ['company_id'], unique=False)
    op.create_unique_constraint('uq_company_setting_key', 'system_settings', ['company_id', 'setting_key'])
    op.create_foreign_key(op.f('fk_system_settings_company_id_companies'), 'system_settings', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('vehicle_loads', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_vehicle_loads_company_id'), 'vehicle_loads', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_vehicle_loads_company_id_companies'), 'vehicle_loads', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('vehicles', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_vehicles_plate_number'), 'vehicles', type_='unique')
    op.create_index(op.f('ix_vehicles_company_id'), 'vehicles', ['company_id'], unique=False)
    op.create_unique_constraint('uq_company_plate_number', 'vehicles', ['company_id', 'plate_number'])
    op.create_foreign_key(op.f('fk_vehicles_company_id_companies'), 'vehicles', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('visit_items', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_visit_items_company_id'), 'visit_items', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_visit_items_company_id_companies'), 'visit_items', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('visit_returns', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_visit_returns_company_id'), 'visit_returns', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_visit_returns_company_id_companies'), 'visit_returns', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('visits', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_visits_company_id'), 'visits', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_visits_company_id_companies'), 'visits', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('work_break_logs', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_work_break_logs_company_id'), 'work_break_logs', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_work_break_logs_company_id_companies'), 'work_break_logs', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('work_sessions', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_work_sessions_company_id'), 'work_sessions', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_work_sessions_company_id_companies'), 'work_sessions', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('zones', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_zone_name_per_governorate'), 'zones', type_='unique')
    op.create_index('idx_uq_zone_company_name_null_gov', 'zones', ['company_id', 'name'], unique=True, postgresql_where=sa.text('governorate_id IS NULL'))
    op.create_index(op.f('ix_zones_company_id'), 'zones', ['company_id'], unique=False)
    op.create_unique_constraint('uq_company_zone_gov', 'zones', ['company_id', 'name', 'governorate_id'])
    op.create_foreign_key(op.f('fk_zones_company_id_companies'), 'zones', 'companies', ['company_id'], ['id'], ondelete='CASCADE')

    # =================================================================
    # المرحلة الانتقالية: Backfill الهوية (Tenant ID) ثم إقفال القيود
    # =================================================================
    from sqlalchemy.sql import text
    conn = op.get_bind()

    # 1. إنشاء شركة افتراضية لالتقاط البيانات القديمة (Legacy)
    conn.execute(text("""
        INSERT INTO companies (name, company_code, is_active, subscription_status, currency_code, timezone, created_at)
        VALUES ('Wanasah Legacy', 'WNS-01', true, 'active', 'JOD', 'Asia/Amman', NOW())
        ON CONFLICT (company_code) DO NOTHING;
    """))

    # 2. جلب معرف الشركة المُنشأة
    company_id_result = conn.execute(text("SELECT id FROM companies WHERE company_code = 'WNS-01' LIMIT 1")).fetchone()
    if company_id_result:
        comp_id = company_id_result[0]

        # 3. حقن الـ Tenant ID في كل الجداول المملوكة للمستأجر ثم إقفال القيد جراحياً
        tables_to_update = [
            'drivers', 'roles', 'user_roles', 'user_location_access', 'branches',
            'zones', 'vehicles', 'vehicle_loads', 'work_sessions', 'session_inventory',
            'shops', 'dispatch_routes', 'visits', 'visit_items', 'visit_returns',
            'shortage_requests', 'offer_rules', 'system_audit_logs', 'inventory_transfers',
            'import_logs', 'work_break_logs', 'products', 'product_variants', 'uom_conversions', 'system_settings'
        ]
        for table in tables_to_update:
            conn.execute(text(f"UPDATE {table} SET company_id = {comp_id} WHERE company_id IS NULL"))
            op.alter_column(table, 'company_id', existing_type=sa.Integer(), nullable=False)

        # 4. بند UOM الإلزامي (QA): لا يجوز إقفال NOT NULL لـ base_uom_id قبل سداد القيم القديمة
        conn.execute(text("INSERT INTO uom (name, code) VALUES ('Pack', 'PACK') ON CONFLICT DO NOTHING;"))
        conn.execute(text("""
            UPDATE product_variants
            SET base_uom_id = (SELECT id FROM uom WHERE code = 'PACK' LIMIT 1)
            WHERE base_uom_id IS NULL;
        """))
        op.alter_column('product_variants', 'base_uom_id', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_zones_company_id_companies'), 'zones', type_='foreignkey')
    op.drop_constraint('uq_company_zone_gov', 'zones', type_='unique')
    op.drop_index(op.f('ix_zones_company_id'), table_name='zones')
    op.drop_index('idx_uq_zone_company_name_null_gov', table_name='zones', postgresql_where=sa.text('governorate_id IS NULL'))
    op.create_unique_constraint(op.f('uq_zone_name_per_governorate'), 'zones', ['name', 'governorate_id'])
    op.drop_column('zones', 'company_id')
    op.drop_constraint(op.f('fk_work_sessions_company_id_companies'), 'work_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_work_sessions_company_id'), table_name='work_sessions')
    op.drop_column('work_sessions', 'company_id')
    op.drop_constraint(op.f('fk_work_break_logs_company_id_companies'), 'work_break_logs', type_='foreignkey')
    op.drop_index(op.f('ix_work_break_logs_company_id'), table_name='work_break_logs')
    op.drop_column('work_break_logs', 'company_id')
    op.drop_constraint(op.f('fk_visits_company_id_companies'), 'visits', type_='foreignkey')
    op.drop_index(op.f('ix_visits_company_id'), table_name='visits')
    op.drop_column('visits', 'company_id')
    op.drop_constraint(op.f('fk_visit_returns_company_id_companies'), 'visit_returns', type_='foreignkey')
    op.drop_index(op.f('ix_visit_returns_company_id'), table_name='visit_returns')
    op.drop_column('visit_returns', 'company_id')
    op.drop_constraint(op.f('fk_visit_items_company_id_companies'), 'visit_items', type_='foreignkey')
    op.drop_index(op.f('ix_visit_items_company_id'), table_name='visit_items')
    op.drop_column('visit_items', 'company_id')
    op.drop_constraint(op.f('fk_vehicles_company_id_companies'), 'vehicles', type_='foreignkey')
    op.drop_constraint('uq_company_plate_number', 'vehicles', type_='unique')
    op.drop_index(op.f('ix_vehicles_company_id'), table_name='vehicles')
    op.create_unique_constraint(op.f('uq_vehicles_plate_number'), 'vehicles', ['plate_number'])
    op.drop_column('vehicles', 'company_id')
    op.drop_constraint(op.f('fk_vehicle_loads_company_id_companies'), 'vehicle_loads', type_='foreignkey')
    op.drop_index(op.f('ix_vehicle_loads_company_id'), table_name='vehicle_loads')
    op.drop_column('vehicle_loads', 'company_id')
    op.drop_constraint(op.f('fk_system_settings_company_id_companies'), 'system_settings', type_='foreignkey')
    op.drop_constraint('uq_company_setting_key', 'system_settings', type_='unique')
    op.drop_index(op.f('ix_system_settings_company_id'), table_name='system_settings')
    op.create_unique_constraint(op.f('uq_system_settings_setting_key'), 'system_settings', ['setting_key'])
    op.drop_column('system_settings', 'company_id')
    op.drop_constraint(op.f('fk_system_audit_logs_company_id_companies'), 'system_audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_system_audit_logs_company_id'), table_name='system_audit_logs')
    op.drop_column('system_audit_logs', 'company_id')
    op.drop_constraint(op.f('fk_shortage_requests_company_id_companies'), 'shortage_requests', type_='foreignkey')
    op.drop_index(op.f('ix_shortage_requests_company_id'), table_name='shortage_requests')
    op.drop_column('shortage_requests', 'company_id')
    op.drop_constraint(op.f('fk_shops_company_id_companies'), 'shops', type_='foreignkey')
    op.drop_index(op.f('ix_shops_company_id'), table_name='shops')
    op.drop_column('shops', 'company_id')
    op.drop_constraint(op.f('fk_session_inventory_company_id_companies'), 'session_inventory', type_='foreignkey')
    op.drop_index(op.f('ix_session_inventory_company_id'), table_name='session_inventory')
    op.drop_column('session_inventory', 'company_id')
    op.drop_constraint(op.f('fk_products_company_id_companies'), 'products', type_='foreignkey')
    op.drop_constraint('uq_company_base_name', 'products', type_='unique')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.create_unique_constraint(op.f('uq_products_base_name'), 'products', ['base_name'])
    op.drop_column('products', 'company_id')
    op.drop_constraint(op.f('fk_product_variants_base_uom_id_uom'), 'product_variants', type_='foreignkey')
    op.drop_constraint(op.f('fk_product_variants_company_id_companies'), 'product_variants', type_='foreignkey')
    op.drop_constraint('uq_company_sku', 'product_variants', type_='unique')
    op.drop_index(op.f('ix_product_variants_company_id'), table_name='product_variants')
    op.create_unique_constraint(op.f('uq_product_variants_sku'), 'product_variants', ['sku'])
    op.drop_column('product_variants', 'base_uom_id')
    op.drop_column('product_variants', 'company_id')
    op.drop_constraint(op.f('fk_offer_rules_company_id_companies'), 'offer_rules', type_='foreignkey')
    op.drop_index(op.f('ix_offer_rules_company_id'), table_name='offer_rules')
    op.drop_column('offer_rules', 'company_id')
    op.drop_constraint(op.f('fk_inventory_transfers_company_id_companies'), 'inventory_transfers', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_transfers_company_id'), table_name='inventory_transfers')
    op.drop_index('uq_pending_transfer', table_name='inventory_transfers', postgresql_where=sa.text("status = 'pending'"))
    op.create_index(op.f('uq_pending_transfer'), 'inventory_transfers', ['work_session_id', 'product_variant_id'], unique=True, postgresql_where="((status)::text = 'pending'::text)")
    op.drop_column('inventory_transfers', 'company_id')
    op.drop_constraint(op.f('fk_import_logs_company_id_companies'), 'import_logs', type_='foreignkey')
    op.drop_index(op.f('ix_import_logs_company_id'), table_name='import_logs')
    op.drop_column('import_logs', 'company_id')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_driver_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_company_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_location_access_location_id'), table_name='user_location_access')
    op.drop_index(op.f('ix_user_location_access_driver_id'), table_name='user_location_access')
    op.drop_index(op.f('ix_user_location_access_company_id'), table_name='user_location_access')
    op.drop_table('user_location_access')
    op.drop_constraint(op.f('fk_drivers_company_id_companies'), 'drivers', type_='foreignkey')
    op.drop_constraint('uq_drivers_company_id', 'drivers', type_='unique')
    op.drop_constraint('uq_company_username', 'drivers', type_='unique')
    op.drop_index(op.f('ix_drivers_company_id'), table_name='drivers')
    op.create_unique_constraint(op.f('uq_drivers_username'), 'drivers', ['username'])
    op.drop_column('drivers', 'company_id')
    op.drop_constraint(op.f('fk_dispatch_routes_company_id_companies'), 'dispatch_routes', type_='foreignkey')
    op.drop_index(op.f('ix_dispatch_routes_company_id'), table_name='dispatch_routes')
    op.drop_index('uq_active_route_per_zone', table_name='dispatch_routes', postgresql_where=sa.text("status IN ('active', 'waiting', 'postponed')"))
    op.create_index(op.f('uq_active_route_per_zone'), 'dispatch_routes', ['zone_id'], unique=True, postgresql_where="((status)::text = ANY ((ARRAY['active'::character varying, 'waiting'::character varying, 'postponed'::character varying])::text[]))")
    op.drop_index('uq_active_route_per_vehicle', table_name='dispatch_routes', postgresql_where=sa.text("status IN ('active', 'waiting', 'postponed')"))
    op.create_index(op.f('uq_active_route_per_vehicle'), 'dispatch_routes', ['vehicle_id'], unique=True, postgresql_where="((status)::text = ANY ((ARRAY['active'::character varying, 'waiting'::character varying, 'postponed'::character varying])::text[]))")
    op.drop_index('uq_active_route_per_driver', table_name='dispatch_routes', postgresql_where=sa.text("status IN ('active', 'waiting', 'postponed')"))
    op.create_index(op.f('uq_active_route_per_driver'), 'dispatch_routes', ['driver_id'], unique=True, postgresql_where="((status)::text = ANY ((ARRAY['active'::character varying, 'waiting'::character varying, 'postponed'::character varying])::text[]))")
    op.drop_column('dispatch_routes', 'company_id')
    op.drop_index(op.f('ix_uom_conversions_company_id'), table_name='uom_conversions')
    op.drop_table('uom_conversions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_roles_company_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_table('uom')
    op.drop_table('platform_admins')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_companies_company_code'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
