"""fix_models_constraints_decimals_and_indexes

Revision ID: 2b482e1ffbb9
Revises: c19550f1c303
Create Date: 2026-08-25 20:22:43.692043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b482e1ffbb9'
down_revision: Union[str, Sequence[str], None] = 'c19550f1c303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_transfers', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('uq_pending_transfer', 'inventory_transfers', ['work_session_id', 'product_variant_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.drop_constraint(op.f('fk_inventory_transfers_admin_id_drivers'), 'inventory_transfers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inventory_transfers_admin_id_drivers'), 'inventory_transfers', 'drivers', ['admin_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_driver_id'), 'refresh_tokens', ['driver_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_unique_constraint(op.f('uq_refresh_tokens_token'), 'refresh_tokens', ['token'])
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.create_index(op.f('ix_token_blacklist_blacklisted_at'), 'token_blacklist', ['blacklisted_at'], unique=False)
    op.create_unique_constraint(op.f('uq_token_blacklist_token'), 'token_blacklist', ['token'])
    op.alter_column('visit_items', 'price_per_unit_at_sale',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.alter_column('visit_items', 'is_cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('visit_returns', 'is_cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visit_returns', 'is_cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('visit_items', 'is_cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('visit_items', 'price_per_unit_at_sale',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.drop_constraint(op.f('uq_token_blacklist_token'), 'token_blacklist', type_='unique')
    op.drop_index(op.f('ix_token_blacklist_blacklisted_at'), table_name='token_blacklist')
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.drop_constraint(op.f('uq_refresh_tokens_token'), 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_driver_id'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.drop_constraint(op.f('fk_inventory_transfers_admin_id_drivers'), 'inventory_transfers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inventory_transfers_admin_id_drivers'), 'inventory_transfers', 'drivers', ['admin_id'], ['id'], ondelete='SET NULL')
    op.drop_index('uq_pending_transfer', table_name='inventory_transfers', postgresql_where=sa.text("status = 'pending'"))
    op.alter_column('inventory_transfers', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
