"""initial_clean_schema

Revision ID: 56c127cae59d
Revises: 
Create Date: 2026-07-29 15:19:20.633562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c127cae59d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('name', name=op.f('uq_countries_name'))
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('can_allow_debt', sa.Boolean(), nullable=False),
    sa.Column('max_debt_limit', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers')),
    sa.UniqueConstraint('username', name=op.f('uq_drivers_username'))
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_name', sa.String(length=150), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('base_name', name=op.f('uq_products_base_name'))
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=50), nullable=False),
    sa.Column('setting_value', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings')),
    sa.UniqueConstraint('setting_key', name=op.f('uq_system_settings_setting_key'))
    )
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_blacklist'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('current_mileage', sa.Integer(), nullable=False),
    sa.Column('next_oil_change', sa.Integer(), nullable=True),
    sa.Column('license_expiry_date', sa.Date(), nullable=True),
    sa.Column('maintenance_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('plate_number', name=op.f('uq_vehicles_plate_number'))
    )
    op.create_table('governorates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_governorates_country_id_countries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_governorates')),
    sa.UniqueConstraint('name', 'country_id', name='uq_governorate_name_per_country')
    )
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_name', sa.String(length=200), nullable=False),
    sa.Column('flavor', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('packs_per_carton', sa.Integer(), nullable=False),
    sa.Column('price_per_carton', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('price_per_pack', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_max_samples_per_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('sku', name=op.f('uq_product_variants_sku'))
    )
    op.create_index(op.f('ix_product_variants_is_active'), 'product_variants', ['is_active'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_refresh_tokens_driver_id_drivers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('system_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['drivers.id'], name=op.f('fk_system_audit_logs_admin_id_drivers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_audit_logs'))
    )
    op.create_index(op.f('ix_system_audit_logs_action_type'), 'system_audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_admin_id'), 'system_audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_target_id'), 'system_audit_logs', ['target_id'], unique=False)
    op.create_table('work_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_latitude', sa.Float(), nullable=True),
    sa.Column('start_longitude', sa.Float(), nullable=True),
    sa.Column('is_authorized_to_sell', sa.Boolean(), nullable=False),
    sa.Column('break_start_time', sa.DateTime(), nullable=True),
    sa.Column('break_end_time', sa.DateTime(), nullable=True),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_work_sessions_driver_id_drivers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_sessions'))
    )
    op.create_index(op.f('ix_work_sessions_driver_id'), 'work_sessions', ['driver_id'], unique=False)
    op.create_index(op.f('ix_work_sessions_end_time'), 'work_sessions', ['end_time'], unique=False)
    op.create_index(op.f('ix_work_sessions_is_settled'), 'work_sessions', ['is_settled'], unique=False)
    op.create_index(op.f('ix_work_sessions_session_date'), 'work_sessions', ['session_date'], unique=False)
    op.create_index('ix_ws_driver_unsettled', 'work_sessions', ['driver_id', 'is_settled', 'end_time'], unique=False)
    op.create_table('inventory_ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_session_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('difference = actual_quantity - expected_quantity', name=op.f('ck_inventory_ledgers_chk_ledger_difference')),
    sa.ForeignKeyConstraint(['admin_id'], ['drivers.id'], name=op.f('fk_inventory_ledgers_admin_id_drivers')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_inventory_ledgers_driver_id_drivers')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_inventory_ledgers_product_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_inventory_ledgers_vehicle_id_vehicles')),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], name=op.f('fk_inventory_ledgers_work_session_id_work_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_ledgers'))
    )
    op.create_index(op.f('ix_inventory_ledgers_work_session_id'), 'inventory_ledgers', ['work_session_id'], unique=False)
    op.create_table('inventory_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_session_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity_packs', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['drivers.id'], name=op.f('fk_inventory_transfers_admin_id_drivers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_inventory_transfers_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], name=op.f('fk_inventory_transfers_work_session_id_work_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_transfers'))
    )
    op.create_table('main_warehouse',
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('available_quantity_packs', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity_packs', sa.Integer(), nullable=False),
    sa.Column('min_threshold_packs', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_main_warehouse_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_variant_id', name=op.f('pk_main_warehouse'))
    )
    op.create_index(op.f('ix_main_warehouse_last_updated'), 'main_warehouse', ['last_updated'], unique=False)
    op.create_table('offer_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=True),
    sa.Column('threshold_quantity', sa.Integer(), nullable=False),
    sa.Column('offer_type', sa.String(length=50), nullable=False),
    sa.Column('bonus_quantity', sa.Integer(), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_offer_rules_product_variant_id_product_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_rules'))
    )
    op.create_index(op.f('ix_offer_rules_product_variant_id'), 'offer_rules', ['product_variant_id'], unique=False)
    op.create_table('session_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_session_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('starting_quantity', sa.Integer(), nullable=False),
    sa.Column('net_transfers', sa.Integer(), nullable=False),
    sa.Column('current_remaining_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_session_inventory_product_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], name=op.f('fk_session_inventory_work_session_id_work_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_inventory')),
    sa.UniqueConstraint('work_session_id', 'product_variant_id', name='uq_session_variant_inv')
    )
    op.create_index(op.f('ix_session_inventory_product_variant_id'), 'session_inventory', ['product_variant_id'], unique=False)
    op.create_table('vehicle_loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_vehicle_loads_product_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_vehicle_loads_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_loads')),
    sa.UniqueConstraint('vehicle_id', 'product_variant_id', name='uq_vehicle_variant_load')
    )
    op.create_table('warehouse_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity_packs', sa.Integer(), nullable=False),
    sa.Column('balance_before_packs', sa.Integer(), nullable=False),
    sa.Column('balance_after_packs', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['drivers.id'], name=op.f('fk_warehouse_ledger_admin_id_drivers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_warehouse_ledger_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse_ledger'))
    )
    op.create_index('idx_ledger_variant_created', 'warehouse_ledger', ['product_variant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_warehouse_ledger_reference_id'), 'warehouse_ledger', ['reference_id'], unique=False)
    op.create_index(op.f('ix_warehouse_ledger_transaction_type'), 'warehouse_ledger', ['transaction_type'], unique=False)
    op.create_index('uq_ledger_supplier_ref', 'warehouse_ledger', ['reference_id', 'product_variant_id'], unique=True, postgresql_where=sa.text("transaction_type = 'INBOUND_SUPPLIER' AND reference_id IS NOT NULL AND reference_id != 'بدون فاتورة'"))
    op.create_table('work_break_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_session_id', sa.Integer(), nullable=False),
    sa.Column('break_start', sa.DateTime(), nullable=False),
    sa.Column('break_end', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], name=op.f('fk_work_break_logs_work_session_id_work_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_break_logs'))
    )
    op.create_index(op.f('ix_work_break_logs_work_session_id'), 'work_break_logs', ['work_session_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('governorate_id', sa.Integer(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('schedule_frequency', sa.String(length=50), nullable=True),
    sa.Column('visit_day', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('custom_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['governorate_id'], ['governorates.id'], name=op.f('fk_zones_governorate_id_governorates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones')),
    sa.UniqueConstraint('name', 'governorate_id', name='uq_zone_name_per_governorate')
    )
    op.create_table('dispatch_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('work_session_id', sa.Integer(), nullable=True),
    sa.Column('dispatch_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_dispatch_routes_driver_id_drivers')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_dispatch_routes_vehicle_id_vehicles')),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], name=op.f('fk_dispatch_routes_work_session_id_work_sessions')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_dispatch_routes_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatch_routes'))
    )
    op.create_index(op.f('ix_dispatch_routes_dispatch_date'), 'dispatch_routes', ['dispatch_date'], unique=False)
    op.create_index(op.f('ix_dispatch_routes_driver_id'), 'dispatch_routes', ['driver_id'], unique=False)
    op.create_index(op.f('ix_dispatch_routes_status'), 'dispatch_routes', ['status'], unique=False)
    op.create_index(op.f('ix_dispatch_routes_vehicle_id'), 'dispatch_routes', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_dispatch_routes_work_session_id'), 'dispatch_routes', ['work_session_id'], unique=False)
    op.create_index(op.f('ix_dispatch_routes_zone_id'), 'dispatch_routes', ['zone_id'], unique=False)
    op.create_index('uq_active_route_per_driver', 'dispatch_routes', ['driver_id'], unique=True, postgresql_where=sa.text("status IN ('active', 'waiting')"))
    op.create_index('uq_active_route_per_vehicle', 'dispatch_routes', ['vehicle_id'], unique=True, postgresql_where=sa.text("status IN ('active', 'waiting')"))
    op.create_index('uq_active_route_per_zone', 'dispatch_routes', ['zone_id'], unique=True, postgresql_where=sa.text("status IN ('active', 'waiting', 'postponed')"))
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['drivers.id'], name=op.f('fk_import_logs_admin_id_drivers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_import_logs_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_logs'))
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('max_debt_limit', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('added_by_driver_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('location_link', sa.String(length=500), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_driver_id'], ['drivers.id'], name=op.f('fk_shops_added_by_driver_id_drivers')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_shops_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops'))
    )
    op.create_index(op.f('ix_shops_zone_id'), 'shops', ['zone_id'], unique=False)
    op.create_table('shortage_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('wait_time', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_shortage_requests_driver_id_drivers')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_shortage_requests_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shortage_requests_shop_id_shops')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_shortage_requests_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shortage_requests'))
    )
    op.create_index(op.f('ix_shortage_requests_driver_id'), 'shortage_requests', ['driver_id'], unique=False)
    op.create_index(op.f('ix_shortage_requests_product_variant_id'), 'shortage_requests', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_shortage_requests_shop_id'), 'shortage_requests', ['shop_id'], unique=False)
    op.create_index(op.f('ix_shortage_requests_status'), 'shortage_requests', ['status'], unique=False)
    op.create_index(op.f('ix_shortage_requests_zone_id'), 'shortage_requests', ['zone_id'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('work_session_id', sa.Integer(), nullable=True),
    sa.Column('visit_timestamp', sa.DateTime(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('amount_before_tax_and_discount', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('discount_applied', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('tax_percentage_applied', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('final_amount_due', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('cash_collected', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('debt_paid', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('no_sale_reason', sa.String(length=200), nullable=True),
    sa.Column('shop_balance_before', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('shop_balance_after', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tax_qr_code', sa.Text(), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_visits_driver_id_drivers')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_visits_shop_id_shops')),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], name=op.f('fk_visits_work_session_id_work_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visits'))
    )
    op.create_index('ix_visit_session_outcome', 'visits', ['work_session_id', 'outcome'], unique=False)
    op.create_index('ix_visit_shop_timestamp', 'visits', ['shop_id', 'visit_timestamp'], unique=False)
    op.create_index(op.f('ix_visits_driver_id'), 'visits', ['driver_id'], unique=False)
    op.create_index(op.f('ix_visits_outcome'), 'visits', ['outcome'], unique=False)
    op.create_index(op.f('ix_visits_shop_id'), 'visits', ['shop_id'], unique=False)
    op.create_index(op.f('ix_visits_status'), 'visits', ['status'], unique=False)
    op.create_index(op.f('ix_visits_visit_timestamp'), 'visits', ['visit_timestamp'], unique=False)
    op.create_index(op.f('ix_visits_work_session_id'), 'visits', ['work_session_id'], unique=False)
    op.create_table('damaged_items_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity_packs', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(length=50), nullable=False),
    sa.Column('source_driver_id', sa.Integer(), nullable=True),
    sa.Column('source_visit_id', sa.Integer(), nullable=True),
    sa.Column('receiving_admin_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_damaged_items_log_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receiving_admin_id'], ['drivers.id'], name=op.f('fk_damaged_items_log_receiving_admin_id_drivers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_driver_id'], ['drivers.id'], name=op.f('fk_damaged_items_log_source_driver_id_drivers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_visit_id'], ['visits.id'], name=op.f('fk_damaged_items_log_source_visit_id_visits'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_damaged_items_log'))
    )
    op.create_table('visit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('packs_quantity', sa.Integer(), nullable=False),
    sa.Column('bonus_quantity', sa.Integer(), nullable=False),
    sa.Column('sample_quantity', sa.Integer(), nullable=False),
    sa.Column('sample_packs_quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_unit_at_sale', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('sample_reason', sa.String(length=255), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_visit_items_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('fk_visit_items_visit_id_visits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visit_items'))
    )
    op.create_index(op.f('ix_visit_items_product_variant_id'), 'visit_items', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_visit_items_visit_id'), 'visit_items', ['visit_id'], unique=False)
    op.create_table('visit_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('packs_quantity', sa.Integer(), nullable=False),
    sa.Column('return_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_visit_returns_product_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('fk_visit_returns_visit_id_visits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visit_returns'))
    )
    op.create_index(op.f('ix_visit_returns_product_variant_id'), 'visit_returns', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_visit_returns_visit_id'), 'visit_returns', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_returns_visit_id'), table_name='visit_returns')
    op.drop_index(op.f('ix_visit_returns_product_variant_id'), table_name='visit_returns')
    op.drop_table('visit_returns')
    op.drop_index(op.f('ix_visit_items_visit_id'), table_name='visit_items')
    op.drop_index(op.f('ix_visit_items_product_variant_id'), table_name='visit_items')
    op.drop_table('visit_items')
    op.drop_table('damaged_items_log')
    op.drop_index(op.f('ix_visits_work_session_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_visit_timestamp'), table_name='visits')
    op.drop_index(op.f('ix_visits_status'), table_name='visits')
    op.drop_index(op.f('ix_visits_shop_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_outcome'), table_name='visits')
    op.drop_index(op.f('ix_visits_driver_id'), table_name='visits')
    op.drop_index('ix_visit_shop_timestamp', table_name='visits')
    op.drop_index('ix_visit_session_outcome', table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_shortage_requests_zone_id'), table_name='shortage_requests')
    op.drop_index(op.f('ix_shortage_requests_status'), table_name='shortage_requests')
    op.drop_index(op.f('ix_shortage_requests_shop_id'), table_name='shortage_requests')
    op.drop_index(op.f('ix_shortage_requests_product_variant_id'), table_name='shortage_requests')
    op.drop_index(op.f('ix_shortage_requests_driver_id'), table_name='shortage_requests')
    op.drop_table('shortage_requests')
    op.drop_index(op.f('ix_shops_zone_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_table('import_logs')
    op.drop_index('uq_active_route_per_zone', table_name='dispatch_routes', postgresql_where=sa.text("status IN ('active', 'waiting', 'postponed')"))
    op.drop_index('uq_active_route_per_vehicle', table_name='dispatch_routes', postgresql_where=sa.text("status IN ('active', 'waiting')"))
    op.drop_index('uq_active_route_per_driver', table_name='dispatch_routes', postgresql_where=sa.text("status IN ('active', 'waiting')"))
    op.drop_index(op.f('ix_dispatch_routes_zone_id'), table_name='dispatch_routes')
    op.drop_index(op.f('ix_dispatch_routes_work_session_id'), table_name='dispatch_routes')
    op.drop_index(op.f('ix_dispatch_routes_vehicle_id'), table_name='dispatch_routes')
    op.drop_index(op.f('ix_dispatch_routes_status'), table_name='dispatch_routes')
    op.drop_index(op.f('ix_dispatch_routes_driver_id'), table_name='dispatch_routes')
    op.drop_index(op.f('ix_dispatch_routes_dispatch_date'), table_name='dispatch_routes')
    op.drop_table('dispatch_routes')
    op.drop_table('zones')
    op.drop_index(op.f('ix_work_break_logs_work_session_id'), table_name='work_break_logs')
    op.drop_table('work_break_logs')
    op.drop_index('uq_ledger_supplier_ref', table_name='warehouse_ledger', postgresql_where=sa.text("transaction_type = 'INBOUND_SUPPLIER' AND reference_id IS NOT NULL AND reference_id != 'بدون فاتورة'"))
    op.drop_index(op.f('ix_warehouse_ledger_transaction_type'), table_name='warehouse_ledger')
    op.drop_index(op.f('ix_warehouse_ledger_reference_id'), table_name='warehouse_ledger')
    op.drop_index('idx_ledger_variant_created', table_name='warehouse_ledger')
    op.drop_table('warehouse_ledger')
    op.drop_table('vehicle_loads')
    op.drop_index(op.f('ix_session_inventory_product_variant_id'), table_name='session_inventory')
    op.drop_table('session_inventory')
    op.drop_index(op.f('ix_offer_rules_product_variant_id'), table_name='offer_rules')
    op.drop_table('offer_rules')
    op.drop_index(op.f('ix_main_warehouse_last_updated'), table_name='main_warehouse')
    op.drop_table('main_warehouse')
    op.drop_table('inventory_transfers')
    op.drop_index(op.f('ix_inventory_ledgers_work_session_id'), table_name='inventory_ledgers')
    op.drop_table('inventory_ledgers')
    op.drop_index('ix_ws_driver_unsettled', table_name='work_sessions')
    op.drop_index(op.f('ix_work_sessions_session_date'), table_name='work_sessions')
    op.drop_index(op.f('ix_work_sessions_is_settled'), table_name='work_sessions')
    op.drop_index(op.f('ix_work_sessions_end_time'), table_name='work_sessions')
    op.drop_index(op.f('ix_work_sessions_driver_id'), table_name='work_sessions')
    op.drop_table('work_sessions')
    op.drop_index(op.f('ix_system_audit_logs_target_id'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_admin_id'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_action_type'), table_name='system_audit_logs')
    op.drop_table('system_audit_logs')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_product_variants_is_active'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_table('governorates')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_table('system_settings')
    op.drop_table('products')
    op.drop_table('drivers')
    op.drop_table('countries')
    # ### end Alembic commands ###
