"""Stage_1_Parent_Guards1

Revision ID: 57b12b6bf85e
Revises: 80b4592450b9
Create Date: 2026-09-02 03:22:02.707641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b12b6bf85e'
down_revision: Union[str, Sequence[str], None] = '80b4592450b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
