"""stage4_batch_expiry

Revision ID: 57e120ab83c1
Revises: 
Create Date: 2026-09-12 02:33:40.139835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e120ab83c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_transfer_headers', sa.Column('transfer_purpose', sa.String(length=50), server_default='WAREHOUSE_BALANCING', nullable=False))
    op.create_index(op.f('ix_inventory_transfer_headers_transfer_purpose'), 'inventory_transfer_headers', ['transfer_purpose'], unique=False)
    op.add_column('product_batches', sa.Column('disposition', sa.String(length=50), server_default='RELEASED', nullable=False))
    op.create_index(op.f('ix_product_batches_disposition'), 'product_batches', ['disposition'], unique=False)
    op.add_column('product_variants', sa.Column('min_shelf_life_days', sa.Integer(), nullable=True))
    
    # Drop and recreate check constraints for stock_status
    status_constraints = [
        ('session_inventory_snapshots', 'chk_session_snapshot_stock_status', "stock_status IN ('AVAILABLE', 'QUARANTINED', 'BLOCKED', 'RECALLED', 'DAMAGED', 'DISPOSAL_PENDING')"),
        ('inventory_balances', 'chk_inv_bal_status', "stock_status IN ('AVAILABLE', 'QUARANTINED', 'BLOCKED', 'RECALLED', 'DAMAGED', 'DISPOSAL_PENDING')"),
        ('inventory_balances', 'chk_inv_bal_damaged_not_reserved', "stock_status <> 'DAMAGED' OR reserved_quantity = 0"),
        ('inventory_movements', 'chk_inv_movement_source_status', "source_stock_status IS NULL OR source_stock_status IN ('AVAILABLE', 'QUARANTINED', 'BLOCKED', 'RECALLED', 'DAMAGED', 'DISPOSAL_PENDING')"),
        ('inventory_movements', 'chk_inv_movement_destination_status', "destination_stock_status IS NULL OR destination_stock_status IN ('AVAILABLE', 'QUARANTINED', 'BLOCKED', 'RECALLED', 'DAMAGED', 'DISPOSAL_PENDING')"),
        ('stocktake_lines', 'chk_stocktake_line_status', "stock_status IN ('AVAILABLE', 'QUARANTINED', 'BLOCKED', 'RECALLED', 'DAMAGED', 'DISPOSAL_PENDING')")
    ]
    for table, name, rule in status_constraints:
        op.drop_constraint(name, table, type_='check')
        op.create_check_constraint(name, table, rule)
        
    # Add new constraints for disposition, transfer_purpose
    op.create_check_constraint('chk_product_batch_disposition', 'product_batches', "disposition IN ('RELEASED', 'QUARANTINED', 'BLOCKED', 'RECALLED')")
    op.create_check_constraint('chk_transfer_header_purpose', 'inventory_transfer_headers', "transfer_purpose IN ('REPLENISHMENT', 'ROUTE_LOAD', 'ROUTE_RETURN', 'WAREHOUSE_BALANCING', 'RETURN_TO_VENDOR', 'QUARANTINE', 'DISPOSAL', 'CONSUMPTION')")
    op.create_check_constraint('chk_product_variant_min_shelf_life', 'product_variants', "min_shelf_life_days IS NULL OR min_shelf_life_days >= 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_product_variant_min_shelf_life', 'product_variants', type_='check')
    op.drop_constraint('chk_transfer_header_purpose', 'inventory_transfer_headers', type_='check')
    op.drop_constraint('chk_product_batch_disposition', 'product_batches', type_='check')
    
    old_status_constraints = [
        ('session_inventory_snapshots', 'chk_session_snapshot_stock_status', "stock_status IN ('AVAILABLE', 'DAMAGED')"),
        ('inventory_balances', 'chk_inv_bal_status', "stock_status IN ('AVAILABLE', 'DAMAGED')"),
        ('inventory_balances', 'chk_inv_bal_damaged_not_reserved', "stock_status <> 'DAMAGED' OR reserved_quantity = 0"),
        ('inventory_movements', 'chk_inv_movement_source_status', "source_stock_status IS NULL OR source_stock_status IN ('AVAILABLE', 'DAMAGED')"),
        ('inventory_movements', 'chk_inv_movement_destination_status', "destination_stock_status IS NULL OR destination_stock_status IN ('AVAILABLE', 'DAMAGED')"),
        ('stocktake_lines', 'chk_stocktake_line_status', "stock_status IN ('AVAILABLE', 'DAMAGED')")
    ]
    for table, name, rule in old_status_constraints:
        op.drop_constraint(name, table, type_='check')
        op.create_check_constraint(name, table, rule)

    op.drop_column('product_variants', 'min_shelf_life_days')
    op.drop_index(op.f('ix_product_batches_disposition'), table_name='product_batches')
    op.drop_column('product_batches', 'disposition')
    op.drop_index(op.f('ix_inventory_transfer_headers_transfer_purpose'), table_name='inventory_transfer_headers')
    op.drop_column('inventory_transfer_headers', 'transfer_purpose')
    # ### end Alembic commands ###
