"""upgrade_gps_precision_and_indexes

Revision ID: 586edd47b83f
Revises: be4ccee5ee8d
Create Date: 2026-08-24 03:14:47.231153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586edd47b83f'
down_revision: Union[str, Sequence[str], None] = 'be4ccee5ee8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shops', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('shops', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=7),
               existing_nullable=True)
    op.create_index('ix_visit_return_composite', 'visit_returns', ['visit_id', 'product_variant_id'], unique=False)
    op.alter_column('visits', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('visits', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=7),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_visits_driver_id_drivers'), 'visits', type_='foreignkey')
    op.create_foreign_key(op.f('fk_visits_driver_id_drivers'), 'visits', 'drivers', ['driver_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('work_sessions', 'start_latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('work_sessions', 'start_longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=7),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_sessions', 'start_longitude',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('work_sessions', 'start_latitude',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_visits_driver_id_drivers'), 'visits', type_='foreignkey')
    op.create_foreign_key(op.f('fk_visits_driver_id_drivers'), 'visits', 'drivers', ['driver_id'], ['id'])
    op.alter_column('visits', 'longitude',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('visits', 'latitude',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_index('ix_visit_return_composite', table_name='visit_returns')
    op.alter_column('shops', 'longitude',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('shops', 'latitude',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
