"""Stage_1_Parent_Guards

Revision ID: 80b4592450b9
Revises: 2462c463c46b
Create Date: 2026-09-02 02:45:54.101680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b4592450b9'
down_revision: Union[str, Sequence[str], None] = '2462c463c46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_product_variants_company_id', 'product_variants', ['company_id', 'id'])
    op.create_unique_constraint('uq_products_company_id', 'products', ['company_id', 'id'])
    op.create_unique_constraint('uq_shops_company_id', 'shops', ['company_id', 'id'])
    op.create_index(op.f('ix_user_location_access_role_id'), 'user_location_access', ['role_id'], unique=False)
    op.create_unique_constraint('uq_vehicles_company_id', 'vehicles', ['company_id', 'id'])
    op.create_unique_constraint('uq_work_sessions_company_id', 'work_sessions', ['company_id', 'id'])
    op.create_unique_constraint('uq_zones_company_id', 'zones', ['company_id', 'id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_zones_company_id', 'zones', type_='unique')
    op.drop_constraint('uq_work_sessions_company_id', 'work_sessions', type_='unique')
    op.drop_constraint('uq_vehicles_company_id', 'vehicles', type_='unique')
    op.drop_index(op.f('ix_user_location_access_role_id'), table_name='user_location_access')
    op.drop_constraint('uq_shops_company_id', 'shops', type_='unique')
    op.drop_constraint('uq_products_company_id', 'products', type_='unique')
    op.drop_constraint('uq_product_variants_company_id', 'product_variants', type_='unique')
    # ### end Alembic commands ###
