"""harden_models_constraints_and_server_defaults

Revision ID: be4ccee5ee8d
Revises: 56c127cae59d
Create Date: 2026-08-14 19:51:54.032613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be4ccee5ee8d'
down_revision: Union[str, Sequence[str], None] = '56c127cae59d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_inventory_ledgers_admin_id_drivers'), 'inventory_ledgers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inventory_ledgers_admin_id_drivers'), 'inventory_ledgers', 'drivers', ['admin_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_shops_added_by_driver_id_drivers'), 'shops', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shops_added_by_driver_id_drivers'), 'shops', 'drivers', ['added_by_driver_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_shops_added_by_driver_id_drivers'), 'shops', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shops_added_by_driver_id_drivers'), 'shops', 'drivers', ['added_by_driver_id'], ['id'])
    op.drop_constraint(op.f('fk_inventory_ledgers_admin_id_drivers'), 'inventory_ledgers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inventory_ledgers_admin_id_drivers'), 'inventory_ledgers', 'drivers', ['admin_id'], ['id'])
    # ### end Alembic commands ###
