"""upgrade_gps_precision_and_indexes

Revision ID: c19550f1c303
Revises: 586edd47b83f
Create Date: 2026-08-24 03:16:01.357053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19550f1c303'
down_revision: Union[str, Sequence[str], None] = '586edd47b83f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_inventory_ledgers_driver_id_drivers'), 'inventory_ledgers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inventory_ledgers_driver_id_drivers'), 'inventory_ledgers', 'drivers', ['driver_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_inventory_ledgers_driver_id_drivers'), 'inventory_ledgers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inventory_ledgers_driver_id_drivers'), 'inventory_ledgers', 'drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###
